#pragma once

#include <lcom/lcf.h>
#include <stddef.h>

/* XPM */
static xpm_row_t const zero[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"            ..                           ",
"           .X...      ..............     ",
"          .XXXX.......XXXXXXXXXXXXX..    ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"          .XXXXXXXXXXXXX.....XXXXXXXXX.  ",
"           .XXXXXXXXXX..     .XXXXXXXX.  ",
"           ...XXXXXXX.       .XXXXXXXXX. ",
"             .XXXXXX.         .XXXXXXXX..",
"            .XXXXXX.          .XXXXXXXXX.",
"           .XXXXXX.           .XXXXXXXXX.",
"          .XXXXXX.            .XXXXXXXXX.",
"         .XXXXXX.             .XXXXXXXXX.",
"        .XXXXXXX.             .XXXXXXXXX.",
"       .XXXXXXX.              .XXXXXXXX. ",
"       .XXXXXXX.              .XXXXXXXX. ",
"      .XXXXXXX.               .XXXXXXXX. ",
"      .XXXXXX..              .XXXXXXXXX. ",
"     .XXXXXXX.               .XXXXXXXXX. ",
"     .XXXXXX.                .XXXXXXXX.  ",
"    .XXXXXXX.                .XXXXXXXX.  ",
"    .XXXXXXX.               .XXXXXXXX.   ",
"   .XXXXXXX.                .XXXXXXXX.   ",
"   .XXXXXXX.                .XXXXXXX.    ",
"  .XXXXXXXX.               .XXXXXXXX.    ",
"  .XXXXXXX.                .XXXXXXXX.    ",
" .XXXXXXXX.               .XXXXXXXX..    ",
" .XXXXXXXX.               .XXXXXXXX.     ",
" .XXXXXXXX.              .XXXXXXXX.      ",
".XXXXXXXX.              .XXXXXXXX..      ",
".XXXXXXXX.              .XXXXXXX..       ",
".XXXXXXXX.             .XXXXXXX..        ",
".XXXXXXXX.             .XXXXXXX.         ",
".XXXXXXXX.            .XXXXXXX.          ",
".XXXXXXXX.           .XXXXXXXX.          ",
" .XXXXXXX.          .XXXXXXXX.           ",
" .XXXXXXXX.        .XXXXXXX..            ",
"  .XXXXXXX.      ..XXXXXXX.              ",
"  .XXXXXXXX.   ..XXXXXXX..               ",
"   .XXXXXXXX...XXXXXXXX..                ",
"    .XXXXXXXXXXXXXXXX..                  ",
"     .XXXXXXXXXXXXX..                    ",
"      ...XXXXXXXX..                      ",
"         ........                        "
};

/* XPM */
static xpm_row_t const one[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                 .            ...        ",
"                .X.      .....XXX.       ",
"               .XXX......XXXXXXXXX.      ",
"               .XXXXXXXXXXXXXXXXXX.      ",
"                .XXXXXXXXXXXXXXXXX.      ",
"                .XXXXXXXXXXXXXXXX.       ",
"                 ..XXXXXXXXXXXXXX.       ",
"                   ..XXXXXXXXXXX.        ",
"                     .XXXXXXXXXX.        ",
"                     .XXXXXXXXXX.        ",
"                    .XXXXXXXXXX.         ",
"                    .XXXXXXXXXX.         ",
"                   .XXXXXXXXXX.          ",
"                   .XXXXXXXXXX.          ",
"                   .XXXXXXXXX.           ",
"                  .XXXXXXXXXX.           ",
"                  .XXXXXXXXX.            ",
"                 .XXXXXXXXXX.            ",
"                 .XXXXXXXXX.             ",
"                 .XXXXXXXXX.             ",
"                .XXXXXXXXX.              ",
"                .XXXXXXXX.               ",
"                .XXXXXXXX.               ",
"               .XXXXXXXX.                ",
"               .XXXXXXXX.                ",
"              .XXXXXXXX.                 ",
"              .XXXXXXX.                  ",
"             .XXXXXXXX.                  ",
"             .XXXXXXX.                   ",
"            .XXXXXXX.                    ",
"            .XXXXXXX.                    ",
"           .XXXXXXX.                     ",
"           .XXXXXX.                      ",
"          .XXXXXX.                       ",
"          .XXXXX.                        ",
"         .XXXXX.                         ",
"         .XXXX.                          ",
"        .XXXX.                           ",
"       .XXXX.                            ",
"      .XXXX.                             ",
"      .XXX.                              ",
"     .XX..                               ",
"    .X..                                 ",
"    ..                                   "
};

/* XPM */
static xpm_row_t const two[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"            .       ................     ",
"           .X.    ..XXXXXXXXXXXXXXXX..   ",
"          .XXX....XXXXXXXXXXXXXXXXXXXX.  ",
"          .XXXXXXXXXXXX.....XXXXXXXXXXX. ",
"         .XXXXXXXXXXXX.     .XXXXXXXXXX. ",
"         .XXXXXXXXXXXX.      .XXXXXXXX.  ",
"          .XXXXXXXXXX.       .XXXXXXXX.  ",
"          .XXXXXXXXX.      ..XXXXXXXX.   ",
"           .XXXXXXX.      .XXXXXXXXXX.   ",
"            ..XXX..      .XXXXXXXXXX.    ",
"              ...       .XXXXXXXXXXX.    ",
"                       .XXXXXXXXXXX.     ",
"                      .XXXXXXXXXXX.      ",
"                     .XXXXXXXXXXXX.      ",
"                    .XXXXXXXXXXXX.       ",
"                   .XXXXXXXXXXXX.        ",
"                  .XXXXXXXXXXXX.         ",
"                 .XXXXXXXXXXXX.          ",
"                .XXXXXXXXXXXX.           ",
"               .XXXXXXXXXXXX.            ",
"              .XXXXXXXXXXXX.             ",
"             .XXXXXXXXXXXX.              ",
"            .XXXXXXXXXXXX.               ",
"           .XXXXXXXXXXXX.                ",
"          .XXXXXXXXXXXX.                 ",
"         .XXXXXXXXXXXX.                  ",
"       ..XXXXXXXXXXXX.                   ",
"      .XXXXXXXXXXXXX.                    ",
"     .XXXXXXXXXXXXX.                .    ",
"    .XXXXXXXXXXXXX.                .X.   ",
"    .XXXXXXXXXXXX.                .XX.   ",
"   .XXXXXXXXXXXX.                 .XX.   ",
"  .XXXXXXXXXXXX.                  XX.    ",
"  .XXXXXXXXXXX.                  .XX.    ",
" .XXXXXXXXXXX.                  .XXX.    ",
" .XXXXXXXXXX.                  .XXX.     ",
" .XXXXXXXXX.                 ..XXXX.     ",
" .XXXXXXXXX.               ..XXXXXX.     ",
"  .XXXXXXXX.             ..XXXXXXX.      ",
"  .XXXXXXXXX.          ..XXXXXXXXX.      ",
"   ..XXXXXXXX..........XXXXXXXXXX.       ",
"     ..XXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"       ...XXXXXXXXXXXXXXXXX.....         ",
"          .................              "
};

/* XPM */
static xpm_row_t const three[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                      ..............     ",
"             .      ..XXXXXXXXXXXXXX..   ",
"            .X......XXXXXXXXXXXXXXXXXX.  ",
"           .XXXXXXXXXXXXX....XXXXXXXXXX. ",
"           .XXXXXXXXXXXX.    .XXXXXXXXX. ",
"           .XXXXXXXXXXX.     .XXXXXXXX.  ",
"           .XXXXXXXXXX.      .XXXXXXXX.  ",
"            .XXXXXXXX.      .XXXXXXXX.   ",
"             .XXXXXX.      .XXXXXXXXX.   ",
"              ......      .XXXXXXXXX.    ",
"                         .XXXXXXXXXX.    ",
"                        .XXXXXXXXXX.     ",
"                       .XXXXXXXXXXX.     ",
"                      .XXXXXXXXXXX.      ",
"                .    .XXXXXXXXXXX.       ",
"               .X.  .XXXXXXXXXXX.        ",
"              .XXX..XXXXXXXXXXX.         ",
"              .XXXXXXXXXXXXXXX.          ",
"             .XXXXXXXXXXXXXXX.           ",
"             .XXXXXXXXXXXXXXXX.          ",
"             .XXXXXXXXXXXXXXXXX.         ",
"              .XXXXXXXXXXXXXXXXX.        ",
"               .XXXXXXXXXXXXXXXX.        ",
"                ...XXXXXXXXXXXXXX.       ",
"                   .XXXXXXXXXXXXX.       ",
"                    .XXXXXXXXXXXXX.      ",
"                     .XXXXXXXXXXXX.      ",
"    .                .XXXXXXXXXXXXX.     ",
"   .X.                .XXXXXXXXXXXX.     ",
"   .X.                .XXXXXXXXXXXXX.    ",
"  .XXX.                .XXXXXXXXXXXX.    ",
"  .XXX.                .XXXXXXXXXXXX.    ",
"  .XXX.                 .XXXXXXXXXXXX.   ",
"  .XXX..                .XXXXXXXXXXXX.   ",
" ..XXXX.                 .XXXXXXXXXXX.   ",
" .XXXXX.                 .XXXXXXXXXX.    ",
" .XXXXX..                .XXXXXXXXX.     ",
"..XXXXXX.               .XXXXXXXXXX.     ",
".XXXXXXXX.              .XXXXXXXXX.      ",
".XXXXXXXXX..          ..XXXXXXXX..       ",
"...XXXXXXXXX..........XXXXXXXX..         ",
"  ....XXXXXXXXXXXXXXXXXXXXX...           ",
"     ...XXXXXXXXXXXXXXX....              ",
"        ...............                  "
};

/* XPM */
static xpm_row_t const four[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                         ...........     ",
"                        .XXXXXXXXXXX.    ",
"                       .XXXXXXXXXXXX.    ",
"                      .XXXXXXXXXXXXX.    ",
"                     .XXXXXXXXXXXXX.     ",
"                    .XXXXXXXXXXXXXX.     ",
"                   .XXXXXXXXXXXXXX.      ",
"                  .XXX.XXXXXXXXXXX.      ",
"                 .XXX..XXXXXXXXXX.       ",
"                .XXX. .XXXXXXXXXX.       ",
"               .XXX. .XXXXXXXXXXX.       ",
"              .XX .  .XXXXXXXXXX.        ",
"             .XXX.   .XXXXXXXXXX.        ",
"            .XXX.   .XXXXXXXXXX.         ",
"          ..XXX.    .XXXXXXXXXX.         ",
"         .XXXX.    .XXXXXXXXXX.          ",
"        .XXX..     .XXXXXXXXX.           ",
"      ..XXX.      .XXXXXXXXXX........... ",
"     .XXXX.........XXXXXXXXXXXXXXXXXXXXX.",
"   ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.. ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXX...XXXXX..   ",
"   .............XXXXXXXXXXX.   .....     ",
"                .XXXXXXXXX.              ",
"                .XXXXXXXXX.              ",
"                .XXXXXXXX.               ",
"               .XXXXXXXXX.               ",
"               .XXXXXXXX.                ",
"              .XXXXXXXX.                 ",
"              .XXXXXXX.                  ",
"             .XXXXXXXX.                  ",
"             .XXXXXXX.                   ",
"            .XXXXXXX.                    ",
"           .XXXXXXX.                     ",
"           .XXXXXX.                      ",
"          .XXXXXX.                       ",
"          .XXXX..                        ",
"         .XXXX.                          ",
"        .XXXX.                           ",
"        .XXX.                            ",
"       .XX..                             ",
"      .X..                               ",
"     .X.                                 ",
"     ..                                  "
};

/* XPM */
static xpm_row_t const five[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                          .....          ",
"                      ....XXXXX..     .  ",
"                    ..XXXXXXXXXXX.   .X. ",
"                   .XXXXXXXXXXXXXX...XXX.",
"                  .XXXXXXXXXXXXXXXXXXXXX.",
"                 .XXXXXXXXXXXXXXXXXXXXXX.",
"                .XXXXXXXXXXXXXXXXXXXXXXX.",
"               .XXXXX.......XXXXXXXXXXX. ",
"              .XXXXX.       .XXXXXXXXX.  ",
"             .XXXXX.         ...XXXX..   ",
"            .XXXXX.             ....     ",
"           .XXXXX.                       ",
"          .XXXXX.                        ",
"         .XXXXX.                         ",
"        .XXXXXXX...                      ",
"       .XXXXXXXXXXX....                  ",
"      .XXXXXXXXXXXXXXXX.....             ",
"     .XXXXXXXXXXXXXXXXXXXXXX...          ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXX..        ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXX.       ",
"      ..XXXXXXXXXXXXXXXXXXXXXXXXXX.      ",
"        ..XXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"          ...XXXXXXXXXXXXXXXXXXXXXX.     ",
"             ....XXXXXXXXXXXXXXXXXXX.    ",
"                 ...XXXXXXXXXXXXXXXX.    ",
"                    ...XXXXXXXXXXXXX.    ",
"                        .XXXXXXXXXXX.    ",
"                         .XXXXXXXXXX.    ",
"   .                     .XXXXXXXXXX.    ",
"  .X.                     .XXXXXXXX.     ",
"  .X.                     .XXXXXXXX.     ",
"  .XX.                    .XXXXXXXX.     ",
" .XXX.                    .XXXXXXX.      ",
" .XXX.                   .XXXXXXXX.      ",
" .XXX.                   .XXXXXXX.       ",
".XXXXX.                 .XXXXXXXX.       ",
".XXXXXX.              ..XXXXXXXX.        ",
".XXXXXXX..          ..XXXXXXXXX.         ",
".XXXXXXXXX.       ..XXXXXXXXX..          ",
" .XXXXXXXXXX......XXXXXXXXX..            ",
"  .XXXXXXXXXXXXXXXXXXXXXX..              ",
"   ...XXXXXXXXXXXXXX.....                ",
"      ...XXXXXXXXX..                     ",
"         .........                       "
};

/* XPM */
static xpm_row_t const six[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                          ..             ",
"                        .. .             ",
"                       .XX.              ",
"                      .XX.               ",
"                    ..XXX.               ",
"                   .XXXX.                ",
"                  .XXXX.                 ",
"                 .XXXX.                  ",
"                .XXXXX.                  ",
"               .XXXXX.                   ",
"              .XXXXX.                    ",
"             .XXXXXX.                    ",
"            .XXXXXX.       ...           ",
"           .XXXXXXX.    ...XXX...        ",
"          .XXXXXXX.  ...XXXXXXXXX..      ",
"          .XXXXXXX...XXXXXXXXXXXXXX.     ",
"         .XXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"         .XXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"        .XXXXXXXXXXXXX......XXXXXXXXX.   ",
"        .XXXXXXXXXXX..      .XXXXXXXX.   ",
"       .XXXXXXXXXXX.         .XXXXXXX.   ",
"       .XXXXXXXXXX.          .XXXXXXX.   ",
"      .XXXXXXXXXX.           .XXXXXXX.   ",
"      .XXXXXXXXXX.           .XXXXXXX.   ",
"     .XXXXXXXXXX.           .XXXXXXX.    ",
"     .XXXXXXXXXX.           .XXXXXXX.    ",
"    .XXXXXXXXXX.            .XXXXXXX.    ",
"    .XXXXXXXXXX.           .XXXXXXX.     ",
"    .XXXXXXXXX.            .XXXXXXX.     ",
"   .XXXXXXXXXX.           .XXXXXXX.      ",
"   .XXXXXXXXXX.           .XXXXXX.       ",
"   .XXXXXXXXX.           .XXXXXX.        ",
"   .XXXXXXXX.           .XXXXXXX.        ",
"   .XXXXXXXX.           .XXXXXX.         ",
"   .XXXXXXXX.          .XXXXXX.          ",
"   .XXXXXXXX.         .XXXXXX.           ",
"   .XXXXXXXX.        .XXXXXX.            ",
"   .XXXXXXXXX.     ..XXXXXXXX.           ",
"    .XXXXXXXXX.....XXXXXXXXXXX.          ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXX.          ",
"     .XXXXXXXXXXXXXXXXXXXXXXXX.          ",
"      ..XXXXXXXXXXXXXXX....XXX.          ",
"        ..XXXXXXXXX....    .X.           ",
"          .........         ..           "
};

/* XPM */
static xpm_row_t const seven[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"        .                   ...          ",
"       .X.           .......XXX.         ",
"      .XXX...........XXXXXXXXXXX.        ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"       .XXXXXXXXXXXXXXXXXXXXXXX.         ",
"       .XXXXXXXXXXXXXXXXXXXXXXX.         ",
"        ...XXXXXX...XXXXXXXXXX.          ",
"           ......  .XXXXXXXXXX.          ",
"                   .XXXXXXXXX.           ",
"                  .XXXXXXXXXX.           ",
"                  .XXXXXXXXX.            ",
"                 .XXXXXXXXXXX..........  ",
"             ....XXXXXXXXXXXXXXXXXXXXXX. ",
"            .XXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"            .XXXXXXXXXXXXXXXXXXXXXXXX.   ",
"             ..XXXXXXXXXXXX..........    ",
"               .XXXXXXXXXX.              ",
"               .XXXXXXXXX.               ",
"               .XXXXXXXXX.               ",
"              .XXXXXXXXX.                ",
"              .XXXXXXXXX.                ",
"             .XXXXXXXXX.                 ",
"             .XXXXXXXXX.                 ",
"             .XXXXXXXX.                  ",
"            .XXXXXXXX.                   ",
"            .XXXXXXXX.                   ",
"           .XXXXXXXX.                    ",
"           .XXXXXXX.                     ",
"          .XXXXXXXX.                     ",
"          .XXXXXXX.                      ",
"         .XXXXXXX.                       ",
"         .XXXXXX.                        ",
"        .XXXXXX.                         ",
"        .XXXXX.                          ",
"       .XXXXX.                           ",
"       .XXXX.                            ",
"      .XXXX.                             ",
"     .XXXX.                              ",
"    .XXXX.                               ",
"   .XXXX.                                ",
"  .XXX..                                 ",
"  .X..                                   ",
"  ..                                     "
};

/* XPM */
static xpm_row_t const eight[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"               .        ............     ",
"              .X.    ...XXXXXXXXXXXX.    ",
"             .XXX....XXXXXXXXXXXXXXXX.   ",
"             .XXXXXXXXXXXX...XXXXXXXXX.  ",
"             .XXXXXXXXXX..   .XXXXXXXXX. ",
"             .XXXXXXXXX.      .XXXXXXXXX.",
"              .XXXXXXX.       .XXXXXXXXX.",
"               .XXXXX.        .XXXXXXXXX.",
"               .XXXXX.       .XXXXXXXXX. ",
"              .XXXXX.       .XXXXXXXXXX. ",
"              .XXXXX.      .XXXXXXXXXX.  ",
"              .XXXXX.    ..XXXXXXXXXXX.  ",
"              .XXXXXX.  .XXXXXXXXXXXX.   ",
"               .XXXXXX..XXXXXXXXXXXX.    ",
"               .XXXXXXXXXXXXXXXXXXX.     ",
"                .XXXXXXXXXXXXXXXXX.      ",
"                 .XXXXXXXXXXXXXXX.       ",
"                  .XXXXXXXXXXXXX.        ",
"                 .XXXXXXXXXXXXX.         ",
"                .XXXXXXXXXXXXX.          ",
"               .XXXXXXXXXXXXXXX.         ",
"              .XXXXXXXXXXXXXXXXX.        ",
"             .XXXXXXXXXXXXXXXXXXX.       ",
"            .XXXXXXXXXXXXXXXXXXXXX.      ",
"          ..XXXXXXXXXXXX.XXXXXXXXX.      ",
"         .XXXXXXXXXXXXX. .XXXXXXXXX.     ",
"        .XXXXXXXXXXXXX.   .XXXXXXXX.     ",
"       .XXXXXXXXXXXXX.    .XXXXXXXXX.    ",
"      .XXXXXXXXXXXXX.      .XXXXXXXX.    ",
"     .XXXXXXXXXXXXX.        .XXXXXXXX.   ",
"    .XXXXXXXXXXXXX.          .XXXXXXX.   ",
"   .XXXXXXXXXXXXX.           .XXXXXXX.   ",
"   .XXXXXXXXXXXX.            .XXXXXXX.   ",
"  .XXXXXXXXXXXX.             .XXXXXXX.   ",
"  .XXXXXXXXXXX.              .XXXXXX.    ",
" .XXXXXXXXXXX.              .XXXXXXX.    ",
" .XXXXXXXXXXX.              .XXXXXX.     ",
" .XXXXXXXXXX.              .XXXXXXX.     ",
"  .XXXXXXXXX.            ..XXXXXXX.      ",
"   .XXXXXXXX.          ..XXXXXXXX.       ",
"    .XXXXXXXX..........XXXXXXXXX.        ",
"     ..XXXXXXXXXXXXXXXXXXXXXX...         ",
"       ....XXXXXXXXXXXXXX....            ",
"           ..............                "
};

/* XPM */
static xpm_row_t const nine[] = {
/* columns rows colors chars-per-pixel */
"41 44 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"           ..         .........          ",
"           .X.    ....XXXXXXXXX..        ",
"          .XXX....XXXXXXXXXXXXXXX..      ",
"          .XXXXXXXXXXXXXXXXXXXXXXXX.     ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"          .XXXXXXXXXXX.....XXXXXXXXX.    ",
"           .XXXXXXXX..     .XXXXXXXXX.   ",
"            .XXXXXX.        .XXXXXXXX.   ",
"           .XXXXXX.         .XXXXXXXX.   ",
"          .XXXXXX.          .XXXXXXXX.   ",
"         .XXXXXX.           .XXXXXXXX.   ",
"        .XXXXXXX.           .XXXXXXXX.   ",
"        .XXXXXX.           .XXXXXXXXX.   ",
"       .XXXXXX.           .XXXXXXXXXX.   ",
"      .XXXXXXX.           .XXXXXXXXXX.   ",
"     .XXXXXXX.            .XXXXXXXXX.    ",
"     .XXXXXXX.           .XXXXXXXXXX.    ",
"    .XXXXXXX.            .XXXXXXXXXX.    ",
"    .XXXXXXX.           .XXXXXXXXXX.     ",
"    .XXXXXXX.           .XXXXXXXXXX.     ",
"   .XXXXXXX.           .XXXXXXXXXX.      ",
"   .XXXXXXX.           .XXXXXXXXXX.      ",
"   .XXXXXXX.          .XXXXXXXXXX.       ",
"   .XXXXXXX.         .XXXXXXXXXXX.       ",
"   .XXXXXXXX.      ..XXXXXXXXXXX.        ",
"   .XXXXXXXXX......XXXXXXXXXXXXX.        ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXX.         ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXX.         ",
"     .XXXXXXXXXXXXXX...XXXXXXX.          ",
"      ..XXXXXXXXX...  .XXXXXXX.          ",
"        ...XXX...    .XXXXXXX.           ",
"           ...       .XXXXXX.            ",
"                    .XXXXXX.             ",
"                    .XXXXX.              ",
"                   .XXXXX.               ",
"                  .XXXXX.                ",
"                  .XXXX.                 ",
"                 .XXXX.                  ",
"                .XXXX.                   ",
"               .XXX..                    ",
"               .XX.                      ",
"              .XX.                       ",
"             . ..                        ",
"             ..                          "
};


/* XPM */
static xpm_row_t const points[] = {
/* columns rows colors chars-per-pixel */
"24 30 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                        ",
"              .         ",
"             .X.        ",
"            .XXX.       ",
"           .XXXXX.      ",
"          .XXXXXXX.     ",
"         .XXXXXXX.      ",
"         .XXXXXX.       ",
"          .XXXX.        ",
"           .XX.         ",
"            ..          ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"          .             ",
"         .X.            ",
"        .XXX.           ",
"       .XXXXX.          ",
"      .XXXXXXX.         ",
"     .XXXXXXX.          ",
"     .XXXXXX.           ",
"      .XXXX.            ",
"       .XX.             ",
"        ..              ",
"                        ",
"                        "
};

/* XPM */
static xpm_row_t const slash[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                        ",
"               ..       ",
"              .XX.      ",
"              .XX.      ",
"             .XX.       ",
"             .XX.       ",
"             .XX.       ",
"            .XXX.       ",
"            .XX.        ",
"            .XX.        ",
"           .XXX.        ",
"           .XX.         ",
"           .XX.         ",
"          .XXX.         ",
"          .XX.          ",
"          .XX.          ",
"         .XXX.          ",
"         .XX.           ",
"        .XXX.           ",
"        .XX.            ",
"        .XX.            ",
"        .XX.            ",
"       .XXX.            ",
"       .XX.             ",
"      .XX.              ",
"       ..               ",
"                        "
};

/* XPM */
static xpm_row_t const point[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"               ...      ",
"              .XXX.     ",
"              .XXX.     ",
"              .XXX.     ",
"               ...      "
};

/* XPM */
static xpm_row_t const zeroS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                        ",
"     ...    ......      ",
"     .XX. ..XXXXXX..    ",
"      .XX.XXXXXXXXXX.   ",
"      .XXXXXXXXXXXXXX.  ",
"       .XXXXX....XXXXX. ",
"       .XXXX.    .XXXX. ",
"      .XXXX.     .XXXXX.",
"      .XXX.      .XXXXX.",
"     .XXX.       .XXXXX.",
"    .XXXX.       .XXXXX.",
"    .XXX.        .XXXXX.",
"   .XXX..        .XXXX. ",
"   .XXX.        .XXXXX. ",
"  .XXXX.        .XXXX.  ",
" .XXXX..        .XXXX.  ",
" .XXXX.        .XXXX.   ",
".XXXX.         .XXXX.   ",
".XXXX.        .XXXX.    ",
".XXXX.        .XXXX.    ",
".XXXX.       .XXXX.     ",
".XXXXX.     .XXXX.      ",
" .XXXX.    .XXX..       ",
" .XXXXX....XXX.         ",
"  .XXXXXXXXXX.          ",
"   ...XXXXX..           ",
"      .....             "
};

/* XPM */
static xpm_row_t const oneS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                        ",
"          .    .....    ",
"         .X....XXXXX.   ",
"         .XXXXXXXXXX.   ",
"         .XXXXXXXXXX.   ",
"          .XXXXXXXXX.   ",
"           .XXXXXXX.    ",
"            .XXXXXX.    ",
"           .XXXXXX.     ",
"           .XXXXXX.     ",
"           .XXXXX.      ",
"          .XXXXXX.      ",
"          .XXXXX.       ",
"         .XXXXXX.       ",
"         .XXXXX.        ",
"        .XXXXXX.        ",
"        .XXXXX.         ",
"       .XXXXX.          ",
"       .XXXXX.          ",
"      .XXXXX.           ",
"      .XXXX.            ",
"     .XXXX.             ",
"    .XXXX.              ",
"   .XXXX.               ",
"   .XX..                ",
"  .XX.                  ",
"  ...                   "
};

/* XPM */
static xpm_row_t const twoS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"             ......     ",
"      ..   ..XXXXXX...  ",
"      .X. .XXXXXXXXXXX. ",
"      .XX.XXX.....XXXX. ",
"      .XXXXX.    .XXXX. ",
"       .XXX.    .XXXX.  ",
"        ...    .XXXXX.  ",
"              .XXXXX.   ",
"             .XXXXX.    ",
"            .XXXXX.     ",
"          ..XXXXX.      ",
"         .XXXXXX.       ",
"        .XXXXXX.        ",
"       .XXXXXX.         ",
"      .XXXXXX.          ",
"     .XXXXXX.           ",
"    .XXXXXX.            ",
"   .XXXXXX.         .   ",
"  .XXXXXX.         .X.  ",
"  .XXXXXX.        .XX.  ",
"  .XXXXX.        ..XX.  ",
"  .XXXXX.       .XXX..  ",
"  .XXXXX.     ..XXXX.   ",
"  .XXXXXX.....XXXX..    ",
"   ..XXXXXXXXXXX..      ",
"     ...XXXXXXX.        ",
"        .......         "
};

/* XPM */
static xpm_row_t const threeS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"              .......   ",
"       ..   ..XXXXXXX.  ",
"      .XX...XXXXXXXXXX. ",
"      .XXXXXXX..XXXXXX. ",
"       .XXXXX.  .XXXXX. ",
"        .XXX.   .XXXX.  ",
"         ...   .XXXXX.  ",
"              .XXXXX.   ",
"             .XXXXXX.   ",
"         .  .XXXXXX.    ",
"        .X..XXXXXX.     ",
"        .XXXXXXXX.      ",
"        .XXXXXXXXX.     ",
"         ..XXXXXXX.     ",
"           .XXXXXXX.    ",
"            .XXXXXXX.   ",
"   .         .XXXXXX.   ",
"  .X.        .XXXXXX.   ",
" .XX.         .XXXXXX.  ",
" .XX.         .XXXXXX.  ",
".XXX.         .XXXXX.   ",
".XXX.         .XXXXX.   ",
".XXXX...     .XXXX..    ",
" .XXXXXX.....XXXXX.     ",
"  ..XXXXXXXXXXXX..      ",
"    ...XXXXXXX..        ",
"       .......          "
};

/* XPM */
static xpm_row_t const fourS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"                        ",
"             .......    ",
"            .XXXXXXX.   ",
"           .XXXXXXXX.   ",
"          .XXXXXXXX.    ",
"         .XXXXXXXXX.    ",
"        .XXX.XXXXXX.    ",
"       .XX...XXXXX.     ",
"      .XX.  .XXXXX.     ",
"     .XX.   .XXXX.      ",
"   ..XX.    .XXXX.      ",
"  .XXX......XXXXX.....  ",
" .XXXXXXXXXXXXXXXXXXXX. ",
".XXXXXXXXXXXXXXXXXXXX.  ",
" .........XXXXX......   ",
"         .XXXX.         ",
"        .XXXXX.         ",
"        .XXXX.          ",
"       .XXXX.           ",
"      .XXXX.            ",
"      .XXX.             ",
"     .XXX.              ",
"    .XXX.               ",
"   .XXX.                ",
"   .XX.                 ",
"   .X.                  ",
"    .                   "
};

/* XPM */
static xpm_row_t const fiveS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"               ...      ",
"           ....XXX.  .. ",
"          .XXXXXXXX..XX.",
"         .XXXXXXXXXXXXX.",
"        .XXXX...XXXXXXX.",
"       .XXX..   .XXXXX. ",
"      .XXX.      .....  ",
"     .XXXX.             ",
"    .XXXX.              ",
"   .XXXXX.....          ",
"   .XXXXXXXXXX....      ",
"   .XXXXXXXXXXXXXX.     ",
"    .XXXXXXXXXXXXXX.    ",
"     .XXXXXXXXXXXXXX.   ",
"      ...XXXXXXXXXXX.   ",
"         ...XXXXXXXXX.  ",
" .          .XXXXXXXX.  ",
".X.          .XXXXXXX.  ",
".XX.          .XXXXX.   ",
".XX.          .XXXX.    ",
".XXX.         .XXXX.    ",
".XXX.        .XXXX.     ",
".XXXX..     ..XXXX.     ",
".XXXXXX.....XXXX..      ",
" .XXXXXXXXXXXXX.        ",
"  ....XXXXXX...         ",
"      ......            "
};

/* XPM */
static xpm_row_t const sixS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"              ..        ",
"             .XX.       ",
"            .XX.        ",
"           .XX.         ",
"          .XXX.         ",
"         .XXX.          ",
"        .XXX.           ",
"       .XXX.            ",
"      .XXX. ........    ",
"     .XXXX..XXXXXXXX.   ",
"     .XXXXXXXXXXXXXXX.  ",
"    .XXXXXXXX....XXXXX. ",
"    .XXXXXX..    .XXXX. ",
"   .XXXXXX.      .XXXX. ",
"  .XXXXXX.       .XXXX. ",
"  .XXXX..        .XXX.  ",
"  .XXXX.         .XXX.  ",
"  .XXX.         .XXX.   ",
" .XXXX.        .XXXX.   ",
" .XXXX.       .XXXX.    ",
" .XXXX.       .XXXX.    ",
" .XXXX.      .XXXX.     ",
"  .XXXX.    .XXXXX.     ",
"  .XXXX.....XXXXXX.     ",
"   .XXXXXXXXXXXX..      ",
"    ..XXXXXXX...        ",
"      .......           "
};

/* XPM */
static xpm_row_t const sevenS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"     .                  ",
"    .X.      ......     ",
"    .XX......XXXXXX.    ",
"    .XXXXXXXXXXXXXX.    ",
"     .XXXXXXXXXXXX.     ",
"      ......XXXXXX.     ",
"           .XXXXX.      ",
"          .XXXXXX...... ",
"        ..XXXXXXXXXXXXX.",
"       .XXXXXXXXXXXXX.. ",
"        ..XXXXX......   ",
"         .XXXXX.        ",
"         .XXXX.         ",
"        .XXXXX.         ",
"        .XXXX.          ",
"       .XXXXX.          ",
"       .XXXX.           ",
"      .XXXX.            ",
"      .XXXX.            ",
"     .XXXX.             ",
"     .XXX.              ",
"    .XXX.               ",
"   .XXX.                ",
"  .XXX.                 ",
"  .X..                  ",
" .X.                    ",
"  .                     "
};

/* XPM */
static xpm_row_t const eightS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"       .     .....      ",
"      .X.  ..XXXXX..    ",
"      .XX..XXXXXXXXX.   ",
"      .XXXXXX....XXXX.  ",
"       .XXXX.   .XXXX.  ",
"       .XXX.    .XXXX.  ",
"       .XXX.   .XXXXX.  ",
"       .XXX.  ..XXXX.   ",
"        .XXX..XXXX..    ",
"        .XXXXXXXX.      ",
"         .XXXXXX.       ",
"        .XXXXXX.        ",
"       .XXXXXXXX.       ",
"      .XXXXXXXXXX.      ",
"     .XXXXX  XXXXX.     ",
"    .XXXX.....XXXXX.    ",
"   .XXXXX.    .XXXX.    ",
"  .XXXX..     .XXXXX.   ",
" .XXXX.       .XXXXX.   ",
".XXXXX.       .XXXXX.   ",
".XXXXX.       .XXXX.    ",
".XXXXX.       .XXXX.    ",
" .XXXX.      ..XXX.     ",
"  .XXXX......XXXX.      ",
"   ..XXXXXXXXXX..       ",
"     .XXXXXXXX.         ",
"      ........          "
};

/* XPM */
static xpm_row_t const nineS[] = {
/* columns rows colors chars-per-pixel */
"24 27 3 1 ",
"  c None",
". c #000000",
"X c #FFFFFF",
/* pixels */
"           .......      ",
"        ...XXXXXXX..    ",
"      ..XXXXXXXXXXXX.   ",
"     .XXXXXX.....XXXX.  ",
"     .XXXXX.    .XXXX.  ",
"     .XXXX.      .XXXX. ",
"    .XXXX.       .XXXX. ",
"    .XXXX.       .XXXX. ",
"   .XXXX.        .XXXX. ",
"   .XXX.         .XXX.  ",
"  .XXX.         .XXXX.  ",
"  .XXX.        ..XXXX.  ",
" .XXXX.       .XXXXXX.  ",
" .XXXX.      .XXXXXX.   ",
" .XXXX.    ..XXXXXX.    ",
" .XXXXX....XXXXXXXX.    ",
"  .XXXXXXXXXXXXXXX.     ",
"   .XXXXXXXX..XXXX.     ",
"    ........ .XXX.      ",
"            .XXX.       ",
"           .XXX.        ",
"          .XXX.         ",
"         .XXX.          ",
"         .XX.           ",
"        .XX.            ",
"       .XX.             ",
"        ..              "
};

static xpm_row_t const star[] = {
/* columns rows colors chars-per-pixel */
"40 40 5 1 ",
"  c None",
". c #000000",
"X c #EDB628",
"o c #F6EC3D",
"O c #FFFFFF",
/* pixels */
"                   ..                   ",
"                  .XX.                  ",
"                 .ooXX.                 ",
"                 .oooXX.                ",
"                .ooooXX.                ",
"                .oOooXX.                ",
"               .oOOoooXX.               ",
"               .OoooooXX.               ",
"               .OoooooXX.               ",
"              .oOooooooXX.              ",
"            ..oOOooooooXX...            ",
"          ..oooOooooooooXXXX..          ",
"         .oooooOooooooooXXXXXX...       ",
" ........oOOOOooooooooooXXXXXXXXX...... ",
".ooOOOOOOOOOooooooooooooXXXXXXXXXXXXXXX.",
".oooooooooooooooooooooooooXXXXXXXXXXXXX.",
".oooooooooooooooooooooooooXXXXXXXXXXXXX.",
" .ooooooooooooooooooooooooXXXXXXXXXXXX. ",
"  .oooooooooooooooooooooooXXXXXXXXXXX.  ",
"   .ooooooooooooooooooooooXXXXXXXXXX.   ",
"    .oooooooooooooooooooooXXXXXXXXX.    ",
"     .ooooooooooooooooooooXXXXXXXX.     ",
"      ..OooooooooooooooooooXXXXXXX.     ",
"        .ooooooooooooooooooXXXXXX.      ",
"        .OOooooooooooooooooXXXXX.       ",
"        .OoooooooooooooooooXXXX.        ",
"        .OoooooooooooooooooXXXX.        ",
"        .OOoooooooooooooooooXXX.        ",
"        .OOoooooooooooooooooXXX.        ",
"       .oOOoooooooooooooooooXXX.        ",
"       .oOOoooooooooooooooooXXX.        ",
"      ..oOoooooooooooooooooooXX..       ",
"      .oOooooooooooooooooooooXXX.       ",
"     .ooOoooooooo.....oooooooXXXX.      ",
"     .ooooooooo..     ..oooooXXXX.      ",
"    .ooooooooo.         .oooooXXXX.     ",
"    .oooooooo.           .oooooXXX.     ",
"    .oooooo..             ..oooXXX.     ",
"    .oooo..                 ..ooXX.     ",
"    .....                     .....     "
};
