#pragma once

#include <lcom/lcf.h>
#include <stddef.h>

/* XPM */
static xpm_row_t const cursor[] = {
/* columns rows colors chars-per-pixel */
"11 16 3 1 ",
"  c None",
". c #000000",
"o c #FFFFFF",
/* pixels */
"..         ",
".o.        ",
".oo.       ",
".ooo.      ",
".oooo.     ",
".ooooo.    ",
".oooooo.   ",
".ooooooo.  ",
".oooooooo. ",
".ooooo.....",
".ooooo.    ",
".oo..o.    ",
".o. .oo.   ",
"..   .o.   ",
".    .oo.  ",
"      ...  "
};

/* XPM */
static xpm_row_t const red_5[] = {
/* columns rows colors chars-per-pixel */
"80 80 3 1 ",
"  c None",
". c #B60909",
"o c #FFFFFF",
/* pixels */
"                     ......................................                     ",
"                     ......................................                     ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"          ............................................................          ",
"          ................oooooooooooooooooooooooooooo................          ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        ...........oooooooooooo..................oooooooooooo...........        ",
"  .................ooooooooooo....................ooooooooooo.................  ",
"  ..............oooooooooooooo....................oooooooooooooo..............  ",
"................oooooooooooooo....................oooooooooooooo................",
"................oooooooo................................oooooooo................",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"..........ooooooooooooo..................................ooooooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........oooooooooo..............oooooooooooo..............oooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........ooooooooo..............oooooooooooooo..............ooooooooo..........",
"..........ooooooooo.........oooooooooooooooooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooooo......ooooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooooo......ooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooooooooooooooooo.........ooooooooo..........",
"..........ooooooooo..............oooooooooooooo..............ooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........oooooooooo..............oooooooooooo..............oooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........ooooooooooooo..................................ooooooooooooo..........",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"................oooooooo................................oooooooo................",
"................oooooooooooooo....................oooooooooooooo................",
"  ..............oooooooooooooo....................oooooooooooooo..............  ",
"  .................ooooooooooo....................ooooooooooo.................  ",
"        ...........oooooooooooo..................oooooooooooo...........        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"          ............................................................          ",
"          ............................................................          ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                     ......................................                     ",
"                     ......................................                     "
};

/* XPM */
static xpm_row_t const red_4[] = {
/* columns rows colors chars-per-pixel */
"60 60 3 1 ",
"  c None",
". c #B60909",
"X c #FFFFFF",
/* pixels */
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"         XXXXXXXXXXXX..................XXXXXXXXXXXX         ",
"         XXXXXXXXXXX....................XXXXXXXXXXX         ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"      XXXXXXXX................................XXXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"XXXXXXXXXXXXX..................................XXXXXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXX..............XXXXXXXXXXXX..............XXXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXX..............XXXXXXXXXXXXXX..............XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXX......XXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXX......XXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX..............XXXXXXXXXXXXXX..............XXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXXX..............XXXXXXXXXXXX..............XXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXXXXX..................................XXXXXXXXXXXXX",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXXX................................XXXXXXXX      ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"         XXXXXXXXXXX....................XXXXXXXXXXX         ",
"         XXXXXXXXXXXX..................XXXXXXXXXXXX         ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 "
};

/* XPM */
static xpm_row_t const red_3[] = {
/* columns rows colors chars-per-pixel */
"42 42 3 1 ",
"  c None",
". c #B60909",
"X c #FFFFFF",
/* pixels */
"            ..................            ",
"           ....................           ",
"           ....................           ",
"           ....................           ",
"     ................................     ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"    ...........XXXXXXXXXXXX...........    ",
"    ...........XXXXXXXXXXXX...........    ",
" ..............XXXXXXXXXXXX.............. ",
"...............XXXXXXXXXXXX...............",
"...............XXXXXXXXXXXX...............",
"..............XXXXXXXXXXXXXX..............",
".........XXXXXXXXXXXXXXXXXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXX......XXXXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXXXX......XXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXXXXXXXXXXXXXXXXX.........",
"..............XXXXXXXXXXXXXX..............",
"...............XXXXXXXXXXXX...............",
"...............XXXXXXXXXXXX...............",
" ..............XXXXXXXXXXXX.............. ",
"    ...........XXXXXXXXXXXX...........    ",
"    ...........XXXXXXXXXXXX...........    ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"     ................................     ",
"           ....................           ",
"           ....................           ",
"           ....................           ",
"            ..................            "
};

/* XPM */
static xpm_row_t const red_2[] = {
/* columns rows colors chars-per-pixel */
"24 24 3 1 ",
"  c None",
". c #B60909",
"X c #FFFFFF",
/* pixels */
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"     XXXXXXXXXXXXXX     ",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXX......XXXXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXXXX......XXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"     XXXXXXXXXXXXXX     ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      "
};

/* XPM */
static xpm_row_t const red_1[] = {
/* columns rows colors chars-per-pixel */
"10 10 2 1 ",
"  c None",
". c #B60909",
/* pixels */
"   ....   ",
"   ....   ",
"  ......  ",
"..........",
"..........",
"..........",
"..........",
"  ......  ",
"   ....   ",
"   ....   "
};


/* XPM */
static xpm_row_t const blue_5[] = {
/* columns rows colors chars-per-pixel */
"80 80 3 1 ",
"  c None",
". c #2044E8",
"o c #FFFFFF",
/* pixels */
"                     ......................................                     ",
"                     ......................................                     ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"          ............................................................          ",
"          ................oooooooooooooooooooooooooooo................          ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        ..................oooooooooooooooooooooooooooo..................        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        ...........oooooooooooo..................oooooooooooo...........        ",
"  .................ooooooooooo....................ooooooooooo.................  ",
"  ..............oooooooooooooo....................oooooooooooooo..............  ",
"................oooooooooooooo....................oooooooooooooo................",
"................oooooooo................................oooooooo................",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"..........ooooooooooooo..................................ooooooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........oooooooooo..............oooooooooooo..............oooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........ooooooooo..............oooooooooooooo..............ooooooooo..........",
"..........ooooooooo.........oooooooooooooooooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooooo......ooooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooo..........ooooooo.........ooooooooo..........",
"..........ooooooooo.........ooooooooo......ooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooo....oooooooooo.........ooooooooo..........",
"..........ooooooooo.........oooooooooooooooooooooooo.........ooooooooo..........",
"..........ooooooooo..............oooooooooooooo..............ooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........ooooooooo...............oooooooooooo...............ooooooooo..........",
"..........oooooooooo..............oooooooooooo..............oooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........ooooooooooooo...........oooooooooooo...........ooooooooooooo..........",
"..........ooooooooooooo..................................ooooooooooooo..........",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"................ooooooo..................................ooooooo................",
"................oooooooo................................oooooooo................",
"................oooooooooooooo....................oooooooooooooo................",
"  ..............oooooooooooooo....................oooooooooooooo..............  ",
"  .................ooooooooooo....................ooooooooooo.................  ",
"        ...........oooooooooooo..................oooooooooooo...........        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        .............oooooooooooooooooooooooooooooooooooooo.............        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"        ...................oooooooooooooooooooooooooo...................        ",
"          ............................................................          ",
"          ............................................................          ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                   ..........................................                   ",
"                     ......................................                     ",
"                     ......................................                     "
};

/* XPM */
static xpm_row_t const blue_4[] = {
/* columns rows colors chars-per-pixel */
"60 60 3 1 ",
"  c None",
". c #2044E8",
"X c #FFFFFF",
/* pixels */
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"                XXXXXXXXXXXXXXXXXXXXXXXXXXXX                ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"         XXXXXXXXXXXX..................XXXXXXXXXXXX         ",
"         XXXXXXXXXXX....................XXXXXXXXXXX         ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"      XXXXXXXX................................XXXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"XXXXXXXXXXXXX..................................XXXXXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXX..............XXXXXXXXXXXX..............XXXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXX..............XXXXXXXXXXXXXX..............XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXX......XXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXX..........XXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXX......XXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXX....XXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXXXX.........XXXXXXXXX",
"XXXXXXXXX..............XXXXXXXXXXXXXX..............XXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXX...............XXXXXXXXXXXX...............XXXXXXXXX",
"XXXXXXXXXX..............XXXXXXXXXXXX..............XXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXXXXX...........XXXXXXXXXXXX...........XXXXXXXXXXXXX",
"XXXXXXXXXXXXX..................................XXXXXXXXXXXXX",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXX..................................XXXXXXX      ",
"      XXXXXXXX................................XXXXXXXX      ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"      XXXXXXXXXXXXXX....................XXXXXXXXXXXXXX      ",
"         XXXXXXXXXXX....................XXXXXXXXXXX         ",
"         XXXXXXXXXXXX..................XXXXXXXXXXXX         ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX           ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 ",
"                 XXXXXXXXXXXXXXXXXXXXXXXXXX                 "
};

/* XPM */
static xpm_row_t const blue_3[] = {
/* columns rows colors chars-per-pixel */
"42 42 3 1 ",
"  c None",
". c #2044E8",
"X c #FFFFFF",
/* pixels */
"            ..................            ",
"           ....................           ",
"           ....................           ",
"           ....................           ",
"     ................................     ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"    ...........XXXXXXXXXXXX...........    ",
"    ...........XXXXXXXXXXXX...........    ",
" ..............XXXXXXXXXXXX.............. ",
"...............XXXXXXXXXXXX...............",
"...............XXXXXXXXXXXX...............",
"..............XXXXXXXXXXXXXX..............",
".........XXXXXXXXXXXXXXXXXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXX......XXXXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXX..........XXXXXXX.........",
".........XXXXXXXXX......XXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXXX....XXXXXXXXXX.........",
".........XXXXXXXXXXXXXXXXXXXXXXXX.........",
"..............XXXXXXXXXXXXXX..............",
"...............XXXXXXXXXXXX...............",
"...............XXXXXXXXXXXX...............",
" ..............XXXXXXXXXXXX.............. ",
"    ...........XXXXXXXXXXXX...........    ",
"    ...........XXXXXXXXXXXX...........    ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"    ..................................    ",
"     ................................     ",
"           ....................           ",
"           ....................           ",
"           ....................           ",
"            ..................            "
};

/* XPM */
static xpm_row_t const blue_2[] = {
/* columns rows colors chars-per-pixel */
"24 24 3 1 ",
"  c None",
". c #2044E8",
"X c #FFFFFF",
/* pixels */
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"     XXXXXXXXXXXXXX     ",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXX......XXXXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXX..........XXXXXXX",
"XXXXXXXXX......XXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXXX....XXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXX",
"     XXXXXXXXXXXXXX     ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      ",
"      XXXXXXXXXXXX      "
};

/* XPM */
static xpm_row_t const blue_1[] = {
/* columns rows colors chars-per-pixel */
"10 10 2 1 ",
"  c None",
". c #2044E8",
/* pixels */
"   ....   ",
"   ....   ",
"  ......  ",
"..........",
"..........",
"..........",
"..........",
"  ......  ",
"   ....   ",
"   ....   "
};

/* XPM */
static xpm_row_t const spikes[] = {
/* columns rows colors chars-per-pixel */
"48 56 3 1 ",
"  c None",
". c #ACACAC",
"X c #C3F0FF",
/* pixels */
"                                ..            ..",
"                                ..            ..",
"                                ..XX        XX..",
"                                ..XX        XX..",
"                              XX....        ....",
"                              XX....        ....",
"                              ......XX      ....",
"                              ......XX      ....",
"                ..            ........    XX....",
"                ..            ........    XX....",
"                ..XX        XX........XX  ......",
"                ..XX        XX........XX  ......",
"              XX....        ............  ......",
"              XX....        ............  ......",
"              ......XX      ............  ......",
"              ......XX      ............  ......",
"..            ........    XX....................",
"..            ........    XX....................",
"..XX        XX........XX  ......................",
"..XX        XX........XX  ......................",
"....        ............  ......................",
"....        ............  ......................",
"....XX      ............  ......................",
"....XX      ............  ......................",
"......    XX....................................",
"......    XX....................................",
"......XX  ......................................",
"......XX  ......................................",
"........  ......................................",
"........  ......................................",
"........  ......................................",
"........  ......................................",
"............................................XXXX",
"............................................XXXX",
"........................................XXXX    ",
"........................................XXXX    ",
"....................................XXXX        ",
"....................................XXXX        ",
"................................XXXX            ",
"................................XXXX            ",
"............................XXXX                ",
"............................XXXX                ",
"........................XXXX                    ",
"........................XXXX                    ",
"....................XXXX                        ",
"....................XXXX                        ",
"................XXXX                            ",
"................XXXX                            ",
"............XXXX                                ",
"............XXXX                                ",
"........XXXX                                    ",
"........XXXX                                    ",
"....XXXX                                        ",
"....XXXX                                        ",
"XXXX                                            ",
"XXXX                                            "
};
