#pragma once

#include <lcom/lcf.h>
#include <stddef.h>

/* XPM */
static xpm_row_t const princess[] = {
/* columns rows colors chars-per-pixel */
"33 82 6 1 ",
"  c None",
". c #656F4D",
"X c #905536",
"o c #C23073",
"O c #E9BD9D",
"+ c #F6B8FA",
/* pixels */
"        XXXXXXXXXXXXX            ",
"        XXXXXXXXXXXXX            ",
"      XXXXXXXXXXXXXXXXX          ",
"      XXXXXXXXXXXXXXXXX          ",
"      XXXXXXXXXXXXXXXXXXX        ",
"      XXXXXXXXXXXXXXXXXXX        ",
"        OOOOXXXXXXXXXXXXXXX      ",
"        OOOOXXXXXXXXXXXXXXX      ",
"        ..OOOOOOXXXXXXXXXXX      ",
"        ..OOOOOOXXXXXXXXXXX      ",
"      OOOOOOOOOOXXXXXXXXXXXXX    ",
"      OOOOOOOOOOXXXXXXXXXXXXX    ",
"        OOOOOOOOXXXXXXXXXXXXX    ",
"        OOOOOOOOXXXXXXXXXXXXX    ",
"        OOOOOOXXXXXXXXXXXXXXX    ",
"        OOOOOOXXXXXXXXXXXXXXX    ",
"         XXXXXXXXXXXXXXXXXXXX    ",
"         XXXXXXXXXXXXXXXXXXXXXX  ",
"         XXXXXXXXXXXXXXXXXXXXXX  ",
"         XXXXXXXXXXXXXXXXXXXXXX  ",
"         XXOOOOOOOOXXXXXXXXXXXX  ",
"         XXOOOOOOOOXXXXXXXXXXXX  ",
"         OOOOOOOOOOOOXXXXXXXXXX  ",
"         OOOOOOOOOOOOXXXXXXXXXX  ",
"       ++++++OOOOOOOOXXXXXXXXXX  ",
"       ++++++OOOOOOOOXXXXXXXXXX  ",
"     ++++++++++++OOOOXXXXXXXXXX  ",
"     ++++++++++++OOOOXXXXXXXXXX  ",
"     ++++++++++++OOOOXXXXXXXXXX  ",
"     ++++++++++++OOOOXXXXXXXX    ",
"       ++++++++++OOOOXXXXXXXX    ",
"       ++++++++++OOOOXXXX        ",
"OOOO     ++++++++OOOOXXXX        ",
"OOOO     ++++++++OOOOXX          ",
"OOOOOOOOOOOOOOOOOOOOOXX          ",
"OOOOOOOOOOOOOOOOOOOOO            ",
"         ++++++++                ",
"         ++++++++                ",
"         ++++++++++              ",
"         ++++++++++              ",
"         ++++++++++++            ",
"         ++++++++++++            ",
"         ++++++++++++++          ",
"         ++++++++++++++          ",
"         ++++++++++++++          ",
"         ++++++++++++++          ",
"         ++++++++++++++++        ",
"         ++++++++++++++++        ",
"         ++++++++++++++++        ",
"         ++++++++++++++++        ",
"         ++++++++++++++++        ",
"        +++++++++++++++++        ",
"        +++++++++++++++++        ",
"        +++++++++++++++++        ",
"        +++++++++++++oooo        ",
"        +++++++++++++oooo        ",
"        +++++++++oooooooo        ",
"        +++++++++oooooooo        ",
"       ++++++oooooooooooooo      ",
"       ++++++oooooooooooooo      ",
"       ++++oooooooooooooooo      ",
"       ++++oooooooooooooooo      ",
"       ++oooooooooooooooooooo    ",
"       ++oooooooooooooooooooo    ",
"       oooooooooooooooooooooo    ",
"       oooooooooooooooooooooo    ",
"     oooooooooooooooooooooooooo  ",
"     oooooooooooooooooooooooooo  ",
"     oooooooooooooooooooooooooo  ",
"     oooooooooooooooooooooooooo  ",
"     oooooooooooooooooooooooooooo",
"     oooooooooooooooooooooooooooo",
"     oooooooooo  ....  oooooooooo",
"     oooooooooo  ....  oooooooooo",
"                 OOOO            ",
"                 OOOO            ",
"               OOOOOO            ",
"               OOOOOO            ",
"             OOOOOOOOOO          ",
"             OOOOOOOOOO          ",
"         OOOOOOOOOOOOOO          ",
"         OOOOOOOOOOOOOO          "
};

/* XPM */
static xpm_row_t const hug[] = {
/* columns rows colors chars-per-pixel */
"39 82 11 1 ",
"  c None",
". c #000000",
"X c #656F4D",
"o c #905536",
"O c #C86100",
"+ c #C23073",
"@ c #FFBB77",
"# c #FFDA68",
"$ c #E9BD9D",
"% c #F6B8FA",
"& c #F8FFFF",
/* pixels */
"                                       ",
"                                       ",
"                                       ",
"                                       ",
"        ########                       ",
"        ########ooooooo                ",
"    ##########ooooooooooo              ",
"    ##########ooooooooooo              ",
"    ######@@@@ooooooooooooo            ",
"    ######@@@@ooooooooooooo            ",
"    ####@@@@@..$$$$oooooooo            ",
"    ####@@@@@.@$$$$oooooooooo          ",
"    ######@@@@XX$$$oooooooooo          ",
"    ######@@@@$X$$$$$oooooooo          ",
"        ####$$$$$$$$$oooooooo          ",
"        ####$$$$$$$$$ooooooooo         ",
"    &&&&&&&&&&$$$$$$$ooooooooo         ",
"    &&&&&&&&&&&$$$$ooooooooooo         ",
"    &&&&&&&&&&$$$$$ooooooooooo         ",
"    &&&&&&@@@@@@@@@@@@@@@@@ooo         ",
"  &&&&&&&@@@@@@@@@@@@@@@@@@@oo         ",
"  &&&&&&@@@@@@@@@@@oooooo@@@oo         ",
"  &&&&&&@@@@@@@@@@oooooooo@@oo         ",
"  &&&&&&$$$&&&&$$$$$$$$$$o@@oo         ",
"&&&&&&&&$$$$$$$$$$$$$$$$$$ooo          ",
"&&&&&&&&$$$$$$$$$%%%%%$$$$ooo          ",
"&&&&&&&&&&&$$$$$$%%%%%$$$$ooo          ",
"&&&&&&&&&&&&&&&&%%%%%%%%$$oo           ",
"&&&&&&&&&&&&&&&%%%%%%%%%$$oo           ",
"&&&&&&&&&&&&&&&%%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&%%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&%%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&%%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&&%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&&%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&&%%%%%%%%%%             ",
"&&&&&&&&&&&&&&&&&%%%%%%%%%             ",
"&&&&&&&&&&&&&&&&&%%%%%%%%%%            ",
"  &&&&&&&&&&&&&&&%%%%%%%%%%            ",
"  &&&&&&&&&&&&&&&&%%%%%%%%%            ",
"  &&&&&&&&&&&&&&&&%%%%%%%%%            ",
"  &&&&&&&&&&&&&&&&%%%%%%%%%%           ",
"  &&&&&&&&&&&&&&&&%%%%%%%%%%           ",
"  &&&&&&&&&&&&&&&&%%%%%%%%%%%          ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%          ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%          ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%%%        ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%%%        ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%%%%%      ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%%%%%      ",
"    &&&&&&&&&&&&&&%%%%%%%%%%%%%++      ",
"    &&&&&&&&&&&&&%%%%%%%%%%%%++++      ",
"    &&&&&&&&&&&&%%%%%%%%%%%%%++++++    ",
"    &&&&&&&&&&&&%%%%%%%%%%%++++++++    ",
"    &&&&&&&&&&&&%%%%%%%%+++++++++++    ",
"    &&&&&&&&&&&&%%%%%%%%+++++++++++    ",
"  &&&&&&&&&&&&&&%%%%%%+++++++++++++    ",
"  &&&&&&&&&&&&&&%%%%%%+++++++++++++    ",
"  &&&&&&&&&&&&&&%%%%+++++++++++++++    ",
"  &&&&&&&&&&&&&&%%++++++++++++++++++   ",
"&&&&&&&&&&&&&&&&%%+++++++++++++++++++  ",
"&&&&&&&&&&&&&&&&+++++++++++++++++++++  ",
"&&&&&&&&&&&&&&+++++++++++++++++++++++  ",
"&&&&&&&&&&&&&&+++++++++++++++++++++++  ",
"&&&&&&&&&&&&&&+++++++++++++++++++++++  ",
"&&&&&&&&&&&&&&+++++++++++++++++++++++  ",
"&&&&&&&&&&&&+++++++++++++++++++++++++  ",
"&&&&&&&&&&&&++++++++++++++++++++++++++ ",
"OO&&&&&&&&OO+++++++++++++++++++++++++++",
"OO&&&&&&&&OO+++++++++++++++++++++++++++",
"  OO&&&&OO      XXXX                   ",
"  OO&&&&OO      XXXX                   ",
"    ....        $$$$                   ",
"    ....        $$$$                   ",
"    @@@@        $$$$$$                 ",
"    @@@@        $$$$$$                 ",
"    @@@@@@      $$$$                   ",
"    @@@@@@    $$$$$$                   ",
"  @@@@@@@@@@@@$$$$                     ",
"  @@@@@@@@@@@@$$$$                     ",
"  @@@@@@@@@@@@@@                       ",
"  @@@@@@@@@@@@@@                       "
};
