#pragma once

#include <lcom/lcf.h>
#include <stddef.h>

/* XPM */
static xpm_row_t const heart[] = {
/* columns rows colors chars-per-pixel */
"20 19 5 1 ",
"  c None",
". c #000000",
"X c #980C0B",
"o c #B60909",
"O c #FFFFFF",
/* pixels */
"   ....      ....   ",
"  .oooo.    .oooX.  ",
" .oooOoo.  .oooooX. ",
".ooooOOoo..oooOOooX.",
".ooooooOoooooooOOoX.",
".oooooooooooooooOoX.",
".oooooooooooooooooX.",
".oooooooooooooooooX.",
" .oooooooooooooooX. ",
" .oooooooooooooooX. ",
"  .oooooooooooooX.  ",
"  .oooooooooooooX.  ",
"   .oooooooooooX.   ",
"    .oooooooooX.    ",
"     .oooooooX.     ",
"      .oooooX.      ",
"       .oooX.       ",
"        .oX.        ",
"         ..         "
};

/* XPM */
static xpm_row_t const l_stand[] = {
/* columns rows colors chars-per-pixel */
"20 80 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"  OOOOOOOOOOOO      ",
"  OOOOOOOOOOOO      ",
"  OOOOOOOOOOOOOO    ",
"  OOOOOOOOOOOOOO    ",
"  ooooOOOOOOOOOO    ",
"  ooooOOOOOOOOOO    ",
"  ..ooooooOOOOOO    ",
"  ..ooooooOOOOOO    ",
"ooooooooooooOOOO    ",
"ooooooooooooOOOO    ",
"  ooooooOOOOOOOO    ",
"  ooooooOOOOOOOO    ",
"  ooooOOOOOO        ",
"  ooooOOOOOO        ",
"      oooooo++oo    ",
"      oooooo++oo    ",
"      oo++++oooo    ",
"      oo++++oooo    ",
"      ++++oooooooo  ",
"      ++++oooooooo  ",
"    XX++oooooooo++  ",
"    XX++oooooooo++  ",
"    ++++oooooooo++  ",
"    ++++oooooooo++  ",
"    ++++oooooooo++  ",
"    ++++oooooooo++  ",
"  ++++++oooooooo++  ",
"  ++++++oooooooo++  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++ooooooXX  ",
"  ++++++++oooooo++  ",
"  ++++++++oooooo++  ",
"  ++++++++oooooo++  ",
"  ++++++++oooooo++  ",
"  ++++++++oooooo++  ",
"  ++++++++oooooo++  ",
"  ++++++++oooo++++  ",
"  ++++++++oooo++++  ",
"  ++++++oooooo++XX  ",
"  ++++++oooooo++XX  ",
"  ++++++oooooo++XX  ",
"  ++++++oooooo++XX  ",
"  ++++++++oooo++XX  ",
"  ++++++++oooo++XX  ",
"  ++++++++++++++    ",
"  ++++++++++++++    ",
"  XX++++++++++++    ",
"  XX++++++++++++    ",
"  XX++++++++++++XX  ",
"  XX++++++++++++XX  ",
"    ++++++++++++XX  ",
"    ++++++++++++XX  ",
"    ++++++++++++++  ",
"    ++++++++++++++  ",
"    XX++++++++++++  ",
"    XX++++++++++++  ",
"      ++++++++++++XX",
"      ++++++++++++XX",
"      XX++++++++++++",
"      XX++++++++++++",
"        XX++++++++XX",
"        XX++++++++XX",
"          XX++++XX  ",
"          XX++++XX  ",
"            ....    ",
"            ....    ",
"            oooo    ",
"            oooo    ",
"          oooooo    ",
"          oooooo    ",
"      oooooooooooo  ",
"      oooooooooooo  ",
"  oooooooooooooooo  ",
"  oooooooooooooooo  "
};

/* XPM */
static xpm_row_t const l_half_run[] = {
/* columns rows colors chars-per-pixel */
"42 76 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"  OOOOOOOOOOO                             ",
"  OOOOOOOOOOO                             ",
"  OOOOOOOOOOOOOO                          ",
"  OOOOOOOOOOOOOO                          ",
"  ooooOOOOOOOOOO                          ",
"  ooooOOOOOOOOOO                          ",
"  ..ooooooOOOOOO                          ",
"  ..ooooooOOOOOO                          ",
"ooooooooooooOOOO                          ",
"ooooooooooooOOOO                          ",
"  ooooooOOOOOOOO                          ",
"  ooooooOOOOOOOO                          ",
"  ooooOOOOOO                              ",
"  ooooOOOOOO                              ",
"      oooooo++oo                          ",
"      oooooo++oo                          ",
"        oo++oooooooo                      ",
"        oo++oooooooo                      ",
"        ++++oooooooooo                    ",
"        ++++oooooooooo                    ",
"        ++++oooooooooooo                  ",
"        ++++oooooooooooo                  ",
"        ++++++oooooooooooo                ",
"        ++++++oooooooooooo                ",
"        XX++++++++oooooooooo              ",
"        XX++++++++oooooooooo              ",
"          ++++++++++oooooooooo            ",
"          ++++++++++oooooooooo            ",
"  XXXXXXXXoo++++++++++oooooo++XX          ",
"  XXXXXXXXoo++++++++++oooooo++XX          ",
"  ooooooXXoo++++++++++oooooo++++          ",
"  ooooooXXoo++++++++++oooooo++++          ",
"  oooooo    XX++++++++oooooo++++          ",
"  oooooo    XX++++++++oooooo++++          ",
"              XX++++++oooo++++++          ",
"              XX++++++oooo++++++          ",
"                  ++oooooo++++++          ",
"                  ++oooooo++++++          ",
"                  oooooooo++++++          ",
"                  oooooooo++++++          ",
"                oooooooo++++++++          ",
"                oooooooo++++++++          ",
"              XX++++++++++++++XX          ",
"              XX++++++++++++++XX          ",
"            XX++++++++++++++++XX          ",
"            XX++++++++++++++++XX          ",
"          XX++++++++++++++++XX            ",
"          XX++++++++++++++++XX            ",
"        XX++++++++++++++++XXXX            ",
"        XX++++++++++++++++XXXX            ",
"        ++++++++++++++++XXXX              ",
"        ++++++++++++++++XXXX              ",
"      XX++++++++++++++XXXX                ",
"      XX++++++++++++++XXXX                ",
"      XX++++++++++++XXXXXX                ",
"      XX++++++++++++XXXXXX                ",
"      XX++++++++++++++++++XX              ",
"      XX++++++++++++++++++XX              ",
"        XX++++++++++++++++++++oo....oooooo",
"        XX++++++++++++++++++++oo....oooooo",
"            ++++++++++++++++++....oooooooo",
"            ++++++++++++++++++....oooooooo",
"                ++++++++++++oo      oooooo",
"                ++++++++++++oo      oooooo",
"                    XX++++oooo        oooo",
"                    XX++++oooo        oooo",
"                        XX....          oo",
"                        XX....          oo",
"                          ....oo        oo",
"                          ....oo        oo",
"                            ..oooo        ",
"                            ..oooo        ",
"                            oooooooo      ",
"                            oooooooo      ",
"                        oooooooooooooo    ",
"                        oooooooooooooo    "
};

/* XPM */
static xpm_row_t const l_run[] = {
/* columns rows colors chars-per-pixel */
"62 80 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"  OOOOOOOOOOOO                                                ",
"  OOOOOOOOOOOO                                                ",
"  OOOOOOOOOOOOOO                                              ",
"  OOOOOOOOOOOOOO                                              ",
"  ooooOOOOOOOOOO                                              ",
"  ooooOOOOOOOOOO                                              ",
"  ..ooooooOOOOOO                                              ",
"  ..ooooooOOOOOO                                              ",
"ooooooooooooOOOO                                              ",
"ooooooooooooOOOO                                              ",
"  ooooooOOOOOOOO                                              ",
"  ooooooOOOOOOOO                                              ",
"  ooooOOOOOO                                                  ",
"  ooooOOOOOO                                                  ",
"      oooooo++XX                                              ",
"      oooooo++XX                                              ",
"      oo++++++++++                                            ",
"      oo++++++++++                                            ",
"      ++++++++oooooo                                          ",
"      ++++++++oooooo                                          ",
"      ++++++++oooooooo                                        ",
"      ++++++++oooooooo                                        ",
"      ++++++++oooooooooo                                      ",
"      ++++++++oooooooooo                                      ",
"      oo++++++++oooooooooo                                    ",
"      oo++++++++oooooooooo                                    ",
"        ++++++++++oooooooooo                                  ",
"        ++++++++++oooooooooo                                  ",
"  XXoooo++++++++++++oooooooooo                                ",
"  XXoooo++++++++++++oooooooooo                                ",
"oooooooooo++++++++++++oooooooo                                ",
"oooooooooo++++++++++++oooooooo                                ",
"oooooo    XX++++++++oooooooooo++                              ",
"oooooo    XX++++++++oooooooooo++                              ",
"            XX++++oooooooooo++++                              ",
"            XX++++oooooooooo++++                              ",
"              oooooooooooo++++++XX                            ",
"              oooooooooooo++++++XX                            ",
"                oooooooo++++++++++                            ",
"                oooooooo++++++++++                            ",
"                oooooo++++++++++++                            ",
"                oooooo++++++++++++                            ",
"              oooooo++++++++++++++                            ",
"              oooooo++++++++++++++                            ",
"              ++++++++++++++++++++                            ",
"              ++++++++++++++++++++                            ",
"            XX++++++++++++++++++++                            ",
"            XX++++++++++++++++++++                            ",
"          XX++++++++++++++++++++++                            ",
"          XX++++++++++++++++++++++                            ",
"          ++++++++++++++++++++++++                            ",
"          ++++++++++++++++++++++++                            ",
"        XX++++++++++XXXX++++++++++                            ",
"        XX++++++++++XXXX++++++++++                            ",
"      XX++++++++++XX  XX++++++++++XX                          ",
"      XX++++++++++XX  XX++++++++++XX                          ",
"      XX++++++++XX    XX++++++++++++++XXXX                    ",
"      XX++++++++XX    XX++++++++++++++XXXX                    ",
"      XX++++++++++XX  XX++++++++++++++++++++XX++....oooooooo  ",
"      XX++++++++++XX  XX++++++++++++++++++++XX++....oooooooo  ",
"      XX++++++++++XX    XX++++++++++++++++++++++....oooooooo  ",
"      XX++++++++++XX    XX++++++++++++++++++++++....oooooooo  ",
"        ++++++++++++XX    XX++++++++++++++++++        oooooo  ",
"        ++++++++++++XX    XX++++++++++++++++++        oooooo  ",
"        XX++++++++++XX                                  oooo  ",
"        XX++++++++++XX                                  oooo  ",
"          ++++++++++XX                                    oo  ",
"          ++++++++++XX                                    oo  ",
"          XX++++++XX                                      oo  ",
"          XX++++++XX                                      oo  ",
"              oooo                                            ",
"              oooo                                            ",
"              ....                                            ",
"              ....                                            ",
"              oooo                                            ",
"              oooo                                            ",
"          oooooooooo                                          ",
"          oooooooooo                                          ",
"      oooooooooooooo                                          ",
"      oooooooooooooo                                          "
};

/* XPM */
static xpm_row_t const l_start_jump[] = {
/* columns rows colors chars-per-pixel */
"64 86 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                  OOOOOOOOOOOO                                  ",
"                  OOOOOOOOOOOO                                  ",
"                OOOOOOOOOOOOOOOO                                ",
"                OOOOOOOOOOOOOOOO                                ",
"                  ooooOOOOOOOOOO                                ",
"                  ooooOOOOOOOOOO                                ",
"                  ..ooooooOOOOOO                                ",
"                  ..ooooooOOOOOO                                ",
"                ooooooooooooOOOO                                ",
"                ooooooooooooOOOO                                ",
"                  ooooooOOOOOOOO                                ",
"                  ooooooOOOOOOOO                                ",
"                  ooooOOOOOO                                    ",
"                  ooooOOOOOO                                    ",
"                      oooooo++XX                                ",
"                      oooooo++XX                                ",
"oooo                  oo++++++++XX                              ",
"oooo                  oo++++++++XX                              ",
"XXoooooo              ++++++++++++XX                            ",
"XXoooooo              ++++++++++++XX                            ",
"    oooooooo          oooooooo++++++                            ",
"    oooooooo          oooooooo++++++                            ",
"      XXoooooooo    oooooooooo++++++XX                          ",
"      XXoooooooo    oooooooooo++++++XX                          ",
"          oooooooooooooooooooo++++++++                          ",
"          oooooooooooooooooooo++++++++                          ",
"              oooooooooooooooo++++++++XX                        ",
"              oooooooooooooooo++++++++XX                        ",
"                oooo    XX++++++++++++XX                        ",
"                oooo    XX++++++++++++XX                        ",
"                        ++++++++++++++++                        ",
"                        ++++++++++++++++                        ",
"                          ++++++++++++++XX                      ",
"                          ++++++++++++++XX                      ",
"                          XX++++++++++++++                      ",
"                          XX++++++++++++++                      ",
"                          XXXX++++++++++++XX                    ",
"                          XXXX++++++++++++XX                    ",
"          XXXX++++++++++++++++++++++++++++++                    ",
"          XXXX++++++++++++++++++++++++++++++                    ",
"      XX++++++++++++++++++++++++++++++++++++XX                  ",
"      XX++++++++++++++++++++++++++++++++++++XX                  ",
"      ++++++++++++++++++++++++++++++++++++++XX                  ",
"      ++++++++++++++++++++++++++++++++++++++XX                  ",
"      ++++++++++++++++++++++XX++++++++++++++++                  ",
"      ++++++++++++++++++++++XX++++++++++++++++                  ",
"      ++++++++++++++++++++++XXXX++++++++++++++                  ",
"      ++++++++++++++++++++++XXXX++++++++++++++                  ",
"        ++++++++++            XX++++++++++++++XX                ",
"        ++++++++++            XX++++++++++++++XX                ",
"        XX++++++++              XX++++++++++++XX                ",
"        XX++++++++              XX++++++++++++XX                ",
"          ++++++++XX            XX++++++++++++++                ",
"          ++++++++XX            XX++++++++++++++                ",
"            XX++++XX              ++++++++++++++                ",
"            XX++++XX              ++++++++++++++                ",
"              ..oo..              XX++++++++++++XX              ",
"              ..oo..              XX++++++++++++XX              ",
"              oooooooo              ++++++++++++XX              ",
"              oooooooo              ++++++++++++XX              ",
"            ooooooooXX              XX++++++++++++              ",
"            ooooooooXX              XX++++++++++++              ",
"        oooooooo                      XX++++++++++XX            ",
"        oooooooo                      XX++++++++++XX            ",
"                                        XX++++++++++XX          ",
"                                        XX++++++++++XX          ",
"                                          ++++++++++++XX        ",
"                                          ++++++++++++XX        ",
"                                          XX++++++++++++XX      ",
"                                          XX++++++++++++XX      ",
"                                            ++++++++++++++      ",
"                                            ++++++++++++++      ",
"                                              ++++++++++++      ",
"                                              ++++++++++++      ",
"                                                XX++++++....    ",
"                                                XX++++++....    ",
"                                                      ....oooo  ",
"                                                      ....oooo  ",
"                                                        ..oooooo",
"                                                        ..oooooo",
"                                                        oooooo  ",
"                                                        oooooo  ",
"                                                      oooooo    ",
"                                                      oooooo    ",
"                                                  oooooo        ",
"                                                  oooooo        "
};

/* XPM */
static xpm_row_t const l_jump[] = {
/* columns rows colors chars-per-pixel */
"94 52 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                                OOOOOOOOOO      ++++oooo                                      ",
"                                OOOOOOOOOO      ++++oooo                                      ",
"                            OOOOOOOOOOOOOOOOOO  ++ooXXXXoo                                    ",
"                            OOOOOOOOOOOOOOOOOO  ++ooXXXXoo                                    ",
"                            OOOOOOOOooooOOOOOOooXXXXXXXXoooo                                  ",
"                            OOOOOOOOooooOOOOOOooXXXXXXXXoooo                                  ",
"                            OOOOOOooooooooOOOOXXXXXXXXXXoo++XX                                ",
"                            OOOOOOooooooooOOOOXXXXXXXXXXoo++XX                                ",
"                            OOOOOOoo..ooooOOooooooXXXXoo++++++XX                              ",
"                            OOOOOOoo..ooooOOooooooXXXXoo++++++XX                              ",
"                              OO      XXoooooooooooooo++++++++XX                              ",
"                              OO      XXoooooooooooooo++++++++XX                              ",
"                                    oooooooooo  oo++++++++++++++                              ",
"                                    oooooooooo  oo++++++++++++++                              ",
"                                  oooooo      oo++++++++++++++++                              ",
"                                  oooooo      oo++++++++++++++++                              ",
"                                              oo++++++++++++++++XX                            ",
"                                              oo++++++++++++++++XX                            ",
"                                                XX++++++++++++++XX                            ",
"                                                XX++++++++++++++XX                            ",
"                                                XX++++++++++++++++                            ",
"                                                XX++++++++++++++++                            ",
"                          XXXX++++++++++++++++++++XX++++++++++++++                            ",
"                          XXXX++++++++++++++++++++XX++++++++++++++                            ",
"                      XXXX++++++++++++++++++++++++++++++++++++++++XX                          ",
"                      XXXX++++++++++++++++++++++++++++++++++++++++XX                          ",
"                  XX++++++++++++++++++++++++++++++++++++++++++++++XX                          ",
"                  XX++++++++++++++++++++++++++++++++++++++++++++++XX                          ",
"                XX++++++++++++++++++++++++++++++++++++++++++++++++XX                          ",
"                XX++++++++++++++++++++++++++++++++++++++++++++++++XX                          ",
"              ++++++++++++++++XX          XXXX++++++++++++++++++++++                          ",
"              ++++++++++++++++XX          XXXX++++++++++++++++++++++                          ",
"              XX++++++++++XX                    XX++++++++++++++++++XX                        ",
"              XX++++++++++XX                    XX++++++++++++++++++XX                        ",
"ooXX      ..oo..XX++++XX                            XX++++++++++++++++                        ",
"ooXX      ..oo..XX++++XX                            XX++++++++++++++++                        ",
"oooooooooooooooo                                        ++++++++++++++XX                      ",
"oooooooooooooooo                                        ++++++++++++++XX                      ",
"  XXoooooooo                                              ++++++++++++XX                      ",
"  XXoooooooo                                              ++++++++++++XX                      ",
"      oooo                                                  ++++++++++++XX            oooo    ",
"      oooo                                                  ++++++++++++XX            oooo    ",
"                                                            XX++++++++++++XXXXXXXX    oooooo  ",
"                                                            XX++++++++++++XXXXXXXX    oooooo  ",
"                                                              ++++++++++++++++++oo..oooooooooo",
"                                                              ++++++++++++++++++oo..oooooooooo",
"                                                                ++++++++++++++++oo..ooXX  XXoo",
"                                                                ++++++++++++++++oo..ooXX  XXoo",
"                                                                    XX++++++++oo              ",
"                                                                    XX++++++++oo              ",
"                                                                          XXXX                ",
"                                                                          XXXX                "
};

/* XPM */
static xpm_row_t const l_end_jump[] = {
/* columns rows colors chars-per-pixel */
"80 68 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                OOOOOOOOOOOO                                                    ",
"                OOOOOOOOOOOO                                                    ",
"              OOOOOOOOOOOOOOOOOO                                                ",
"              OOOOOOOOOOOOOOOOOO                                                ",
"              OOOOOOOOOOooOOOOOO  oooooo                                        ",
"              OOOOOOOOOOooOOOOOO  oooooo                                        ",
"              OOOOOOOOooooOOOOOOoooo++++oooooo                                  ",
"              OOOOOOOOooooOOOOOOoooo++++oooooo                                  ",
"              OOOOOOooooooooOOOOoooo++++oooooooooooo                            ",
"              OOOOOOooooooooOOOOoooo++++oooooooooooo                            ",
"              OOOOOOoo..ooooOO  oo++++++oooooooooooooooo                        ",
"              OOOOOOoo..ooooOO  oo++++++oooooooooooooooo                        ",
"                OO      oo      ++++++++++oooooooooooooooooo                    ",
"                OO      oo      ++++++++++oooooooooooooooooo                    ",
"                                ++++++++++++++++oooooooooooooooo                ",
"                                ++++++++++++++++oooooooooooooooo                ",
"                                  XX++++++++++++++++XX  oooooooooooo            ",
"                                  XX++++++++++++++++XX  oooooooooooo            ",
"                                  XX++++++++++++++++XX        oooooooooo        ",
"                                  XX++++++++++++++++XX        oooooooooo        ",
"                                    XX++++++++++++++++XX          oooooooooo    ",
"                                    XX++++++++++++++++XX          oooooooooo    ",
"                                      XX++++++++++++++XX              oooooooooo",
"                                      XX++++++++++++++XX              oooooooooo",
"                                        ++++++++++++++XX                  XXXooo",
"                                        ++++++++++++++XX                  XXXooo",
"                                    XXXXXX++++++++++++++                        ",
"                                    XXXXXX++++++++++++++                        ",
"                                XXXX++++++++++++++++++++                        ",
"                                XXXX++++++++++++++++++++                        ",
"                                ++++++++++++++++++++++++                        ",
"                                ++++++++++++++++++++++++                        ",
"                          ++++++++++++++++++++++++++++XX                        ",
"                          ++++++++++++++++++++++++++++XX                        ",
"                      XX++++++++++++++++++++++++++++++                          ",
"                      XX++++++++++++++++++++++++++++++                          ",
"                    XX++++++++++++++++++++++++++++++XX    XXoo                  ",
"                    XX++++++++++++++++++++++++++++++XX    XXoo                  ",
"                  ++++++++++++++++XX++++++++++++++XX    ..oooo                  ",
"                  ++++++++++++++++XX++++++++++++++XX    ..oooo                  ",
"                ++++++++++++++++XX++++++++++++++XX++++....oooooo                ",
"                ++++++++++++++++XX++++++++++++++XX++++....oooooo                ",
"                ++++++++++++++XX  ++++++++++++XX++++++++    oooo                ",
"                ++++++++++++++XX  ++++++++++++XX++++++++    oooo                ",
"              ++++++++++++++    XX++++++++++++++++++++XX      oo                ",
"              ++++++++++++++    XX++++++++++++++++++++XX      oo                ",
"              ++++++++++XX      ++++++++++++++++++XX                            ",
"              ++++++++++XX      ++++++++++++++++++XX                            ",
"            ++++++++++          ++++++++++++++++                                ",
"            ++++++++++          ++++++++++++++++                                ",
"            ++++++++XX          XX++++++++++XXXX                                ",
"            ++++++++XX          XX++++++++++XXXX                                ",
"          XX++++++++              XX++++XXXX                                    ",
"          XX++++++++              XX++++XXXX                                    ",
"          XX++++++XX                                                            ",
"          XX++++++XX                                                            ",
"          ++++++XX                                                              ",
"          ++++++XX                                                              ",
"          ..oo                                                                  ",
"          ..oo                                                                  ",
"      XXoooo..                                                                  ",
"      XXoooo..                                                                  ",
"oooooooooooo                                                                    ",
"oooooooooooo                                                                    ",
"  oooooooooo                                                                    ",
"  oooooooooo                                                                    ",
"      oooo                                                                      ",
"      oooo                                                                      "
};

/* XPM */
static xpm_row_t const l_fall[] = {
/* columns rows colors chars-per-pixel */
"34 72 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"oooo      OOOOOOOOOO              ",
"oooo      OOOOOOOOOO              ",
"  ooooOOOOOOOOOOOOOOOO            ",
"  ooooOOOOOOOOOOOOOOOO            ",
"  ooooooOOOOOOOOOOOOOO            ",
"  ooooooOOOOOOOOOOOOOO            ",
"    ooooooOOOOOOOOOOOOOO          ",
"    ooooooOOOOOOOOOOOOOO          ",
"      ooooooOOOOOOOOOOXX          ",
"      ooooooOOOOOOOOOOXX          ",
"        ooooooOOOO++++++          ",
"        ooooooOOOO++++++          ",
"        oooooooo++++++++          ",
"        oooooooo++++++++          ",
"          oooooo++++++++++XX      ",
"          oooooo++++++++++XX      ",
"            oooo++++++++++++XX    ",
"            oooo++++++++++++XX    ",
"              oo++++++++++++++XX  ",
"              oo++++++++++++++XX  ",
"              oo++++++++++++++++XX",
"              oo++++++++++++++++XX",
"                XX++++++++++++++XX",
"                XX++++++++++++++XX",
"                XX++++++++++++++XX",
"                XX++++++++++++++XX",
"                XX++++++++++++++XX",
"                XX++++++++++++++XX",
"                XX++++++++++++XX  ",
"                XX++++++++++++XX  ",
"                ++++++++++++++XX  ",
"                ++++++++++++++XX  ",
"                XX++++++++++++XX  ",
"                XX++++++++++++XX  ",
"                XX++++++++++++XX  ",
"                XX++++++++++++XX  ",
"              XX++++++++++++XX    ",
"              XX++++++++++++XX    ",
"            XX++++++++++++++XX    ",
"            XX++++++++++++++XX    ",
"            XX++++++++++++XX      ",
"            XX++++++++++++XX      ",
"          XX++++++++++++XX        ",
"          XX++++++++++++XX        ",
"          XX++++++++++XX          ",
"          XX++++++++++XX          ",
"          ++++++++++++            ",
"          ++++++++++++            ",
"        XX++++++++++++            ",
"        XX++++++++++++            ",
"        XX++++++++++++            ",
"        XX++++++++++++            ",
"        XX++++++++++++            ",
"        XX++++++++++++            ",
"        XX++++++++++XX            ",
"        XX++++++++++XX            ",
"          ++++++++XX              ",
"          ++++++++XX              ",
"          oo++++++                ",
"          oo++++++                ",
"            ....                  ",
"            ....                  ",
"            oooo                  ",
"            oooo                  ",
"          oooooooo                ",
"          oooooooo                ",
"          oooooooo                ",
"          oooooooo                ",
"        oooooo                    ",
"        oooooo                    ",
"        oooo                      ",
"        oooo                      "
};

/* XPM */
static xpm_row_t const r_stand[] = {
/* columns rows colors chars-per-pixel */
"20 80 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"      OOOOOOOOOOOO  ",
"      OOOOOOOOOOOO  ",
"    OOOOOOOOOOOOOO  ",
"    OOOOOOOOOOOOOO  ",
"    OOOOOOOOOOoooo  ",
"    OOOOOOOOOOoooo  ",
"    OOOOOOoooooo..  ",
"    OOOOOOoooooo..  ",
"    OOOOoooooooooooo",
"    OOOOoooooooooooo",
"    OOOOOOOOoooooo  ",
"    OOOOOOOOoooooo  ",
"        OOOOOOoooo  ",
"        OOOOOOoooo  ",
"    oo++oooooo      ",
"    oo++oooooo      ",
"    oooo++++oo      ",
"    oooo++++oo      ",
"  oooooooo++++      ",
"  oooooooo++++      ",
"  ++oooooooo++XX    ",
"  ++oooooooo++XX    ",
"  ++oooooooo++++    ",
"  ++oooooooo++++    ",
"  ++oooooooo++++    ",
"  ++oooooooo++++    ",
"  ++oooooooo++++++  ",
"  ++oooooooo++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  XXoooooo++++++++  ",
"  ++oooooo++++++++  ",
"  ++oooooo++++++++  ",
"  ++oooooo++++++++  ",
"  ++oooooo++++++++  ",
"  ++oooooo++++++++  ",
"  ++oooooo++++++++  ",
"  ++++oooo++++++++  ",
"  ++++oooo++++++++  ",
"  XX++oooooo++++++  ",
"  XX++oooooo++++++  ",
"  XX++oooooo++++++  ",
"  XX++oooooo++++++  ",
"  XX++oooo++++++++  ",
"  XX++oooo++++++++  ",
"    ++++++++++++++  ",
"    ++++++++++++++  ",
"    ++++++++++++XX  ",
"    ++++++++++++XX  ",
"  XX++++++++++++XX  ",
"  XX++++++++++++XX  ",
"  XX++++++++++++    ",
"  XX++++++++++++    ",
"  ++++++++++++++    ",
"  ++++++++++++++    ",
"  ++++++++++++XX    ",
"  ++++++++++++XX    ",
"XX++++++++++++      ",
"XX++++++++++++      ",
"++++++++++++XX      ",
"++++++++++++XX      ",
"XX++++++++XX        ",
"XX++++++++XX        ",
"  XX++++XX          ",
"  XX++++XX          ",
"    ....            ",
"    ....            ",
"    oooo            ",
"    oooo            ",
"    oooooo          ",
"    oooooo          ",
"  oooooooooooo      ",
"  oooooooooooo      ",
"  oooooooooooooooo  ",
"  oooooooooooooooo  "
};

/* XPM */
static xpm_row_t const r_half_run[] = {
/* columns rows colors chars-per-pixel */
"42 76 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                             OOOOOOOOOOO  ",
"                             OOOOOOOOOOO  ",
"                          OOOOOOOOOOOOOO  ",
"                          OOOOOOOOOOOOOO  ",
"                          OOOOOOOOOOoooo  ",
"                          OOOOOOOOOOoooo  ",
"                          OOOOOOoooooo..  ",
"                          OOOOOOoooooo..  ",
"                          OOOOoooooooooooo",
"                          OOOOoooooooooooo",
"                          OOOOOOOOoooooo  ",
"                          OOOOOOOOoooooo  ",
"                              OOOOOOoooo  ",
"                              OOOOOOoooo  ",
"                          oo++oooooo      ",
"                          oo++oooooo      ",
"                      oooooooo++oo        ",
"                      oooooooo++oo        ",
"                    oooooooooo++++        ",
"                    oooooooooo++++        ",
"                  oooooooooooo++++        ",
"                  oooooooooooo++++        ",
"                oooooooooooo++++++        ",
"                oooooooooooo++++++        ",
"              oooooooooo++++++++XX        ",
"              oooooooooo++++++++XX        ",
"            oooooooooo++++++++++          ",
"            oooooooooo++++++++++          ",
"          XX++oooooo++++++++++ooXXXXXXXX  ",
"          XX++oooooo++++++++++ooXXXXXXXX  ",
"          ++++oooooo++++++++++ooXXoooooo  ",
"          ++++oooooo++++++++++ooXXoooooo  ",
"          ++++oooooo++++++++XX    oooooo  ",
"          ++++oooooo++++++++XX    oooooo  ",
"          ++++++oooo++++++XX              ",
"          ++++++oooo++++++XX              ",
"          ++++++oooooo++                  ",
"          ++++++oooooo++                  ",
"          ++++++oooooooo                  ",
"          ++++++oooooooo                  ",
"          ++++++++oooooooo                ",
"          ++++++++oooooooo                ",
"          XX++++++++++++++XX              ",
"          XX++++++++++++++XX              ",
"          XX++++++++++++++++XX            ",
"          XX++++++++++++++++XX            ",
"            XX++++++++++++++++XX          ",
"            XX++++++++++++++++XX          ",
"            XXXX++++++++++++++++XX        ",
"            XXXX++++++++++++++++XX        ",
"              XXXX++++++++++++++++        ",
"              XXXX++++++++++++++++        ",
"                XXXX++++++++++++++XX      ",
"                XXXX++++++++++++++XX      ",
"                XXXXXX++++++++++++XX      ",
"                XXXXXX++++++++++++XX      ",
"              XX++++++++++++++++++XX      ",
"              XX++++++++++++++++++XX      ",
"oooooo....oo++++++++++++++++++++XX        ",
"oooooo....oo++++++++++++++++++++XX        ",
"oooooooo....++++++++++++++++++            ",
"oooooooo....++++++++++++++++++            ",
"oooooo      oo++++++++++++                ",
"oooooo      oo++++++++++++                ",
"oooo        oooo++++XX                    ",
"oooo        oooo++++XX                    ",
"oo          ....XX                        ",
"oo          ....XX                        ",
"oo        oo....                          ",
"oo        oo....                          ",
"        oooo..                            ",
"        oooo..                            ",
"      oooooooo                            ",
"      oooooooo                            ",
"    oooooooooooooo                        ",
"    oooooooooooooo                        "
};

/* XPM */
static xpm_row_t const r_run[] = {
/* columns rows colors chars-per-pixel */
"62 80 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                                                OOOOOOOOOOOO  ",
"                                                OOOOOOOOOOOO  ",
"                                              OOOOOOOOOOOOOO  ",
"                                              OOOOOOOOOOOOOO  ",
"                                              OOOOOOOOOOoooo  ",
"                                              OOOOOOOOOOoooo  ",
"                                              OOOOOOoooooo..  ",
"                                              OOOOOOoooooo..  ",
"                                              OOOOoooooooooooo",
"                                              OOOOoooooooooooo",
"                                              OOOOOOOOoooooo  ",
"                                              OOOOOOOOoooooo  ",
"                                                  OOOOOOoooo  ",
"                                                  OOOOOOoooo  ",
"                                              XX++oooooo      ",
"                                              XX++oooooo      ",
"                                            ++++++++++oo      ",
"                                            ++++++++++oo      ",
"                                          oooooo++++++++      ",
"                                          oooooo++++++++      ",
"                                        oooooooo++++++++      ",
"                                        oooooooo++++++++      ",
"                                      oooooooooo++++++++      ",
"                                      oooooooooo++++++++      ",
"                                    oooooooooo++++++++oo      ",
"                                    oooooooooo++++++++oo      ",
"                                  oooooooooo++++++++++        ",
"                                  oooooooooo++++++++++        ",
"                                oooooooooo++++++++++++ooooXX  ",
"                                oooooooooo++++++++++++ooooXX  ",
"                                oooooooo++++++++++++oooooooooo",
"                                oooooooo++++++++++++oooooooooo",
"                              ++oooooooooo++++++++XX    oooooo",
"                              ++oooooooooo++++++++XX    oooooo",
"                              ++++oooooooooo++++XX            ",
"                              ++++oooooooooo++++XX            ",
"                            XX++++++oooooooooooo              ",
"                            XX++++++oooooooooooo              ",
"                            ++++++++++oooooooo                ",
"                            ++++++++++oooooooo                ",
"                            ++++++++++++oooooo                ",
"                            ++++++++++++oooooo                ",
"                            ++++++++++++++oooooo              ",
"                            ++++++++++++++oooooo              ",
"                            ++++++++++++++++++++              ",
"                            ++++++++++++++++++++              ",
"                            ++++++++++++++++++++XX            ",
"                            ++++++++++++++++++++XX            ",
"                            ++++++++++++++++++++++XX          ",
"                            ++++++++++++++++++++++XX          ",
"                            ++++++++++++++++++++++++          ",
"                            ++++++++++++++++++++++++          ",
"                            ++++++++++XXXX++++++++++XX        ",
"                            ++++++++++XXXX++++++++++XX        ",
"                          XX++++++++++XX  XX++++++++++XX      ",
"                          XX++++++++++XX  XX++++++++++XX      ",
"                    XXXX++++++++++++++XX    XX++++++++XX      ",
"                    XXXX++++++++++++++XX    XX++++++++XX      ",
"  oooooooo....++XX++++++++++++++++++++XX  XX++++++++++XX      ",
"  oooooooo....++XX++++++++++++++++++++XX  XX++++++++++XX      ",
"  oooooooo....++++++++++++++++++++++XX    XX++++++++++XX      ",
"  oooooooo....++++++++++++++++++++++XX    XX++++++++++XX      ",
"  oooooo        ++++++++++++++++++XX    XX++++++++++++        ",
"  oooooo        ++++++++++++++++++XX    XX++++++++++++        ",
"  oooo                                  XX++++++++++XX        ",
"  oooo                                  XX++++++++++XX        ",
"  oo                                    XX++++++++++          ",
"  oo                                    XX++++++++++          ",
"  oo                                      XX++++++XX          ",
"  oo                                      XX++++++XX          ",
"                                            oooo              ",
"                                            oooo              ",
"                                            ....              ",
"                                            ....              ",
"                                            oooo              ",
"                                            oooo              ",
"                                          oooooooooo          ",
"                                          oooooooooo          ",
"                                          oooooooooooooo      ",
"                                          oooooooooooooo      "
};

/* XPM */
static xpm_row_t const r_start_jump[] = {
/* columns rows colors chars-per-pixel */
"64 86 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                                  OOOOOOOOOOOO                  ",
"                                  OOOOOOOOOOOO                  ",
"                                OOOOOOOOOOOOOOOO                ",
"                                OOOOOOOOOOOOOOOO                ",
"                                OOOOOOOOOOoooo                  ",
"                                OOOOOOOOOOoooo                  ",
"                                OOOOOOoooooo..                  ",
"                                OOOOOOoooooo..                  ",
"                                OOOOoooooooooooo                ",
"                                OOOOoooooooooooo                ",
"                                OOOOOOOOoooooo                  ",
"                                OOOOOOOOoooooo                  ",
"                                    OOOOOOoooo                  ",
"                                    OOOOOOoooo                  ",
"                                XX++oooooo                      ",
"                                XX++oooooo                      ",
"                              XX++++++++oo                  oooo",
"                              XX++++++++oo                  oooo",
"                            XX++++++++++++              ooooooXX",
"                            XX++++++++++++              ooooooXX",
"                            ++++++oooooooo          oooooooo    ",
"                            ++++++oooooooo          oooooooo    ",
"                          XX++++++oooooooooo    ooooooooXX      ",
"                          XX++++++oooooooooo    ooooooooXX      ",
"                          ++++++++oooooooooooooooooooo          ",
"                          ++++++++oooooooooooooooooooo          ",
"                        XX++++++++oooooooooooooooo              ",
"                        XX++++++++oooooooooooooooo              ",
"                        XX++++++++++++XX    oooo                ",
"                        XX++++++++++++XX    oooo                ",
"                        ++++++++++++++++                        ",
"                        ++++++++++++++++                        ",
"                      XX++++++++++++++                          ",
"                      XX++++++++++++++                          ",
"                      ++++++++++++++XX                          ",
"                      ++++++++++++++XX                          ",
"                    XX++++++++++++XXXX                          ",
"                    XX++++++++++++XXXX                          ",
"                    ++++++++++++++++++++++++++++++XXXX          ",
"                    ++++++++++++++++++++++++++++++XXXX          ",
"                  XX++++++++++++++++++++++++++++++++++++XX      ",
"                  XX++++++++++++++++++++++++++++++++++++XX      ",
"                  XX++++++++++++++++++++++++++++++++++++++      ",
"                  XX++++++++++++++++++++++++++++++++++++++      ",
"                  ++++++++++++++++XX++++++++++++++++++++++      ",
"                  ++++++++++++++++XX++++++++++++++++++++++      ",
"                  ++++++++++++++XXXX++++++++++++++++++++++      ",
"                  ++++++++++++++XXXX++++++++++++++++++++++      ",
"                XX++++++++++++++XX            ++++++++++        ",
"                XX++++++++++++++XX            ++++++++++        ",
"                XX++++++++++++XX              ++++++++XX        ",
"                XX++++++++++++XX              ++++++++XX        ",
"                ++++++++++++++XX            XX++++++++          ",
"                ++++++++++++++XX            XX++++++++          ",
"                ++++++++++++++              XX++++XX            ",
"                ++++++++++++++              XX++++XX            ",
"              XX++++++++++++XX              ..oo..              ",
"              XX++++++++++++XX              ..oo..              ",
"              XX++++++++++++              oooooooo              ",
"              XX++++++++++++              oooooooo              ",
"              ++++++++++++XX              XXoooooooo            ",
"              ++++++++++++XX              XXoooooooo            ",
"            XX++++++++++XX                      oooooooo        ",
"            XX++++++++++XX                      oooooooo        ",
"          XX++++++++++XX                                        ",
"          XX++++++++++XX                                        ",
"        XX++++++++++++                                          ",
"        XX++++++++++++                                          ",
"      XX++++++++++++XX                                          ",
"      XX++++++++++++XX                                          ",
"      ++++++++++++++                                            ",
"      ++++++++++++++                                            ",
"      ++++++++++++                                              ",
"      ++++++++++++                                              ",
"    ....++++++XX                                                ",
"    ....++++++XX                                                ",
"  oooo....                                                      ",
"  oooo....                                                      ",
"oooooo..                                                        ",
"oooooo..                                                        ",
"  oooooo                                                        ",
"  oooooo                                                        ",
"    oooooo                                                      ",
"    oooooo                                                      ",
"        oooooo                                                  ",
"        oooooo                                                  "
};

/* XPM */
static xpm_row_t const r_jump[] = {
/* columns rows colors chars-per-pixel */
"94 52 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                                      oooo++++      OOOOOOOOOO                                ",
"                                      oooo++++      OOOOOOOOOO                                ",
"                                    ooXXXXoo++  OOOOOOOOOOOOOOOOOO                            ",
"                                    ooXXXXoo++  OOOOOOOOOOOOOOOOOO                            ",
"                                  ooooXXXXXXXXooOOOOOOooooOOOOOOOO                            ",
"                                  ooooXXXXXXXXooOOOOOOooooOOOOOOOO                            ",
"                                XX++ooXXXXXXXXXXOOOOooooooooOOOOOO                            ",
"                                XX++ooXXXXXXXXXXOOOOooooooooOOOOOO                            ",
"                              XX++++++ooXXXXooooooOOoooo..ooOOOOOO                            ",
"                              XX++++++ooXXXXooooooOOoooo..ooOOOOOO                            ",
"                              XX++++++++ooooooooooooooXX      OO                              ",
"                              XX++++++++ooooooooooooooXX      OO                              ",
"                              ++++++++++++++oo  oooooooooo                                    ",
"                              ++++++++++++++oo  oooooooooo                                    ",
"                              ++++++++++++++++oo      oooooo                                  ",
"                              ++++++++++++++++oo      oooooo                                  ",
"                            XX++++++++++++++++oo                                              ",
"                            XX++++++++++++++++oo                                              ",
"                            XX++++++++++++++XX                                                ",
"                            XX++++++++++++++XX                                                ",
"                            ++++++++++++++++XX                                                ",
"                            ++++++++++++++++XX                                                ",
"                            ++++++++++++++XX++++++++++++++++++++XXXX                          ",
"                            ++++++++++++++XX++++++++++++++++++++XXXX                          ",
"                          XX++++++++++++++++++++++++++++++++++++++++XXXX                      ",
"                          XX++++++++++++++++++++++++++++++++++++++++XXXX                      ",
"                          XX++++++++++++++++++++++++++++++++++++++++++++++XX                  ",
"                          XX++++++++++++++++++++++++++++++++++++++++++++++XX                  ",
"                          XX++++++++++++++++++++++++++++++++++++++++++++++++XX                ",
"                          XX++++++++++++++++++++++++++++++++++++++++++++++++XX                ",
"                          ++++++++++++++++++++++XXXX          XX++++++++++++++++              ",
"                          ++++++++++++++++++++++XXXX          XX++++++++++++++++              ",
"                        XX++++++++++++++++++XX                    XX++++++++++XX              ",
"                        XX++++++++++++++++++XX                    XX++++++++++XX              ",
"                        ++++++++++++++++XX                            XX++++XX..oo..      XXoo",
"                        ++++++++++++++++XX                            XX++++XX..oo..      XXoo",
"                      XX++++++++++++++                                        oooooooooooooooo",
"                      XX++++++++++++++                                        oooooooooooooooo",
"                      XX++++++++++++                                              ooooooooXX  ",
"                      XX++++++++++++                                              ooooooooXX  ",
"    oooo            XX++++++++++++                                                  oooo      ",
"    oooo            XX++++++++++++                                                  oooo      ",
"  oooooo    XXXXXXXX++++++++++++XX                                                            ",
"  oooooo    XXXXXXXX++++++++++++XX                                                            ",
"oooooooooo..oo++++++++++++++++++                                                              ",
"oooooooooo..oo++++++++++++++++++                                                              ",
"ooXX  XXoo..oo++++++++++++++++                                                                ",
"ooXX  XXoo..oo++++++++++++++++                                                                ",
"              oo++++++++XX                                                                    ",
"              oo++++++++XX                                                                    ",
"                XXXX                                                                          ",
"                XXXX                                                                          "
};

/* XPM */
static xpm_row_t const r_end_jump[] = {
/* columns rows colors chars-per-pixel */
"80 68 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"                                                    OOOOOOOOOOOO                ",
"                                                    OOOOOOOOOOOO                ",
"                                                OOOOOOOOOOOOOOOOOO              ",
"                                                OOOOOOOOOOOOOOOOOO              ",
"                                        oooooo  OOOOOOooOOOOOOOOOO              ",
"                                        oooooo  OOOOOOooOOOOOOOOOO              ",
"                                  oooooo++++ooooOOOOOOooooOOOOOOOO              ",
"                                  oooooo++++ooooOOOOOOooooOOOOOOOO              ",
"                            oooooooooooo++++ooooOOOOooooooooOOOOOO              ",
"                            oooooooooooo++++ooooOOOOooooooooOOOOOO              ",
"                        oooooooooooooooo++++++oo  OOoooo..ooOOOOOO              ",
"                        oooooooooooooooo++++++oo  OOoooo..ooOOOOOO              ",
"                    oooooooooooooooooo++++++++++      oo      OO                ",
"                    oooooooooooooooooo++++++++++      oo      OO                ",
"                oooooooooooooooo++++++++++++++++                                ",
"                oooooooooooooooo++++++++++++++++                                ",
"            oooooooooooo  XX++++++++++++++++XX                                  ",
"            oooooooooooo  XX++++++++++++++++XX                                  ",
"        oooooooooo        XX++++++++++++++++XX                                  ",
"        oooooooooo        XX++++++++++++++++XX                                  ",
"    oooooooooo          XX++++++++++++++++XX                                    ",
"    oooooooooo          XX++++++++++++++++XX                                    ",
"oooooooooo              XX++++++++++++++XX                                      ",
"oooooooooo              XX++++++++++++++XX                                      ",
"oooXXX                  XX++++++++++++++                                        ",
"oooXXX                  XX++++++++++++++                                        ",
"                        ++++++++++++++XXXXXX                                    ",
"                        ++++++++++++++XXXXXX                                    ",
"                        ++++++++++++++++++++XXXX                                ",
"                        ++++++++++++++++++++XXXX                                ",
"                        ++++++++++++++++++++++++                                ",
"                        ++++++++++++++++++++++++                                ",
"                        XX++++++++++++++++++++++++++++                          ",
"                        XX++++++++++++++++++++++++++++                          ",
"                          ++++++++++++++++++++++++++++++XX                      ",
"                          ++++++++++++++++++++++++++++++XX                      ",
"                  ooXX    XX++++++++++++++++++++++++++++++XX                    ",
"                  ooXX    XX++++++++++++++++++++++++++++++XX                    ",
"                  oooo..    XX++++++++++++++XX++++++++++++++++                  ",
"                  oooo..    XX++++++++++++++XX++++++++++++++++                  ",
"                oooooo....++++XX++++++++++++++XX++++++++++++++++                ",
"                oooooo....++++XX++++++++++++++XX++++++++++++++++                ",
"                oooo    ++++++++XX++++++++++++  XX++++++++++++++                ",
"                oooo    ++++++++XX++++++++++++  XX++++++++++++++                ",
"                oo      XX++++++++++++++++++++XX    ++++++++++++++              ",
"                oo      XX++++++++++++++++++++XX    ++++++++++++++              ",
"                            XX++++++++++++++++++      XX++++++++++              ",
"                            XX++++++++++++++++++      XX++++++++++              ",
"                                ++++++++++++++++          ++++++++++            ",
"                                ++++++++++++++++          ++++++++++            ",
"                                XXXX++++++++++XX          XX++++++++            ",
"                                XXXX++++++++++XX          XX++++++++            ",
"                                    XXXX++++XX              ++++++++XX          ",
"                                    XXXX++++XX              ++++++++XX          ",
"                                                            XX++++++XX          ",
"                                                            XX++++++XX          ",
"                                                              XX++++++          ",
"                                                              XX++++++          ",
"                                                                  oo..          ",
"                                                                  oo..          ",
"                                                                  ..ooooXX      ",
"                                                                  ..ooooXX      ",
"                                                                    oooooooooooo",
"                                                                    oooooooooooo",
"                                                                    oooooooooo  ",
"                                                                    oooooooooo  ",
"                                                                      oooo      ",
"                                                                      oooo      "
};

/* XPM */
static xpm_row_t const r_fall[] = {
/* columns rows colors chars-per-pixel */
"34 72 6 1 ",
"  c None",
". c #000000",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #F8FFFF",
/* pixels */
"              OOOOOOOOOO      oooo",
"              OOOOOOOOOO      oooo",
"            OOOOOOOOOOOOOOOOoooo  ",
"            OOOOOOOOOOOOOOOOoooo  ",
"            OOOOOOOOOOOOOOoooooo  ",
"            OOOOOOOOOOOOOOoooooo  ",
"          OOOOOOOOOOOOOOoooooo    ",
"          OOOOOOOOOOOOOOoooooo    ",
"          XXOOOOOOOOOOoooooo      ",
"          XXOOOOOOOOOOoooooo      ",
"          ++++++OOOOoooooo        ",
"          ++++++OOOOoooooo        ",
"          ++++++++oooooooo        ",
"          ++++++++oooooooo        ",
"      XX++++++++++oooooo          ",
"      XX++++++++++oooooo          ",
"    XX++++++++++++oooo            ",
"    XX++++++++++++oooo            ",
"  XX++++++++++++++oo              ",
"  XX++++++++++++++oo              ",
"XX++++++++++++++++oo              ",
"XX++++++++++++++++oo              ",
"XX++++++++++++++XX                ",
"XX++++++++++++++XX                ",
"XX++++++++++++++XX                ",
"XX++++++++++++++XX                ",
"XX++++++++++++++XX                ",
"XX++++++++++++++XX                ",
"  XX++++++++++++XX                ",
"  XX++++++++++++XX                ",
"  XX++++++++++++++                ",
"  XX++++++++++++++                ",
"  XX++++++++++++XX                ",
"  XX++++++++++++XX                ",
"  XX++++++++++++XX                ",
"  XX++++++++++++XX                ",
"    XX++++++++++++XX              ",
"    XX++++++++++++XX              ",
"    XX++++++++++++++XX            ",
"    XX++++++++++++++XX            ",
"      XX++++++++++++XX            ",
"      XX++++++++++++XX            ",
"        XX++++++++++++XX          ",
"        XX++++++++++++XX          ",
"          XX++++++++++XX          ",
"          XX++++++++++XX          ",
"            ++++++++++++          ",
"            ++++++++++++          ",
"            ++++++++++++XX        ",
"            ++++++++++++XX        ",
"            ++++++++++++XX        ",
"            ++++++++++++XX        ",
"            ++++++++++++XX        ",
"            ++++++++++++XX        ",
"            XX++++++++++XX        ",
"            XX++++++++++XX        ",
"              XX++++++++          ",
"              XX++++++++          ",
"                ++++++oo          ",
"                ++++++oo          ",
"                  ....            ",
"                  ....            ",
"                  oooo            ",
"                  oooo            ",
"                oooooooo          ",
"                oooooooo          ",
"                oooooooo          ",
"                oooooooo          ",
"                    oooooo        ",
"                    oooooo        ",
"                      oooo        ",
"                      oooo        "
};

/* XPM */
static xpm_row_t const r_stand_fight[] = {
/* columns rows colors chars-per-pixel */
"58 74 8 1 ",
"  c None",
". c #000000",
"X c #B60909",
"o c #FFBA78",
"O c #FFD969",
"+ c #D8D8D8",
"@ c #F5FCFC",
"# c #F8FFFF",
/* pixels */
"                  OOOOOOOOOOOO                            ",
"                  OOOOOOOOOOOO                            ",
"                OOOOOOOOOOOOOOOO                          ",
"                OOOOOOOOOOOOOOOO                          ",
"                OOOOOOOOOOoooo                            ",
"                OOOOOOOOOOoooo                            ",
"                OOOOOOoooooo..                            ",
"                OOOOOOoooooo..                            ",
"                OOOOoooooooooooo                          ",
"                OOOOoooooooooooo                          ",
"                OOOOOOOOoooooo                            ",
"                OOOOOOOOoooooo                            ",
"            ########OOOOOOoooo                            ",
"            ########OOOOOOoooo                            ",
"        oooooooo######oo##                                ",
"        oooooooo######oo##                                ",
"        oooooooo##########                                ",
"        oooooooo##########                                ",
"      oooooooo############                          ++++++",
"      oooooooo############                          ++++++",
"    oooooooo##############                        ++++    ",
"    oooooooo##############                        ++++    ",
"    oooooooo##############                    ++++++      ",
"    oooooooo##############                    ++++++      ",
"      oooooooo############oooo              ++++          ",
"      oooooooo############oooo              ++++          ",
"        oooooooo##########oooooooo      ++++++            ",
"        oooooooo##########oooooooo      ++++++            ",
"      ####oooooo########    oooooooooo++++                ",
"      ####oooooo########    oooooooooo++++                ",
"      ####oooooo######          XXooXX++                  ",
"      ####oooooo######          XXooXX++                  ",
"      ################                                    ",
"      ################                                    ",
"    ####################                                  ",
"    ####################                                  ",
"    ######################                                ",
"    ######################                                ",
"    #######################@                              ",
"    ########################                              ",
"    ##########################                            ",
"    ##########################                            ",
"    ############################                          ",
"    ############################                          ",
"      ############################                        ",
"      ############################                        ",
"      ##############################                      ",
"      ##############################                      ",
"      ##############  ################                    ",
"      ##############  ################                    ",
"      ##############  ################                    ",
"      ##############  ################                    ",
"      ############      ##############                    ",
"      ############      ##############                    ",
"    ##############      ##############                    ",
"    ##############      ##############                    ",
"    ############        ##############                    ",
"    ############        ##############                    ",
"  ##############          ############                    ",
"  ##############          ############                    ",
"##############              ########                      ",
"##############              ########                      ",
"############                  ....                        ",
"############                  ....                        ",
"  ########                    oooo                        ",
"  ########                    oooo                        ",
"    ....                    oooooooo                      ",
"    ....                    oooooooo                      ",
"    oooo                    oooooooooo                    ",
"    oooo                    oooooooooo                    ",
"  oooooooo                        oooooooo                ",
"  oooooooo                        oooooooo                ",
"  oooooooooooo                                            ",
"  oooooooooooo                                            "
};

/* XPM */
static xpm_row_t const r_fight[] = {
/* columns rows colors chars-per-pixel */
"132 60 8 1 ",
"  c None",
". c #000000",
"X c #B60909",
"o c #C76100",
"O c #FFBA78",
"+ c #FFD969",
"@ c #D8D8D8",
"# c #F8FFFF",
/* pixels */
"                                                        ++++++++++++++                                                              ",
"                                                        ++++++++++++++                                                              ",
"                                                      ++++++++++++++++++++                                                          ",
"                                                      ++++++++++++++++++++                                                          ",
"                  OOOOOO                            ++++++++++++OOOOOO  ++                                                          ",
"                  OOOOOO                            ++++++++++++OOOOOO  ++                                                          ",
"                  OOOOOOOOOOOO                      ++++++++OOOOOOOO..                                                              ",
"                  OOOOOOOOOOOO                      ++++++++OOOOOOOO..                                                              ",
"                        OOOOOOOOOOOOOOOOOOOOOO######oo++++OOOOOOOOOOOOOO                                                            ",
"                        OOOOOOOOOOOOOOOOOOOOOO######oo++++OOOOOOOOOOOOOO                                                            ",
"                            OOOOOOOOOOOOOOOOOO########++++++++OOOOOOOO                                                              ",
"                            OOOOOOOOOOOOOOOOOO########++++++++OOOOOOOO                                                              ",
"                                      ##OOOOOO######OOOOOO++++++OOOOoooooooooooooooo                                                ",
"                                      ##OOOOOO######OOOOOO++++++OOOOoooooooooooooooo                                                ",
"                                      ##############OOOOOOOOOOOOooooooOOOOOOOOOOOOOOOOOOOOOOOOOO@@                                  ",
"                                      ##############OOOOOOOOOOOOooooooOOOOOOOOOOOOOOOOOOOOOOOOOO@@                                  ",
"                                      ##############OO########                            XXOOXX@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"                                      ##############OO########                            XXOOXX@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"                                    ########################                                    @@                                  ",
"                                    ########################                                    @@                                  ",
"                                  ######################                                                                            ",
"                                  ######################                                                                            ",
"                                ####################                                                                                ",
"                                ####################                                                                                ",
"                              ####################                                                                                  ",
"                              ####################                                                                                  ",
"                              ##################                                                                                    ",
"                              ##################                                                                                    ",
"                            ####################                                                                                    ",
"                            ####################                                                                                    ",
"                            ##########################                                                                              ",
"                            ##########################                                                                              ",
"                          ####################################                                                                      ",
"                          ####################################                                                                      ",
"                          ##########################################                                                                ",
"                          ##########################################                                                                ",
"                        ############################################                                                                ",
"                        ############################################                                                                ",
"                        ############################################                                                                ",
"                        ############################################                                                                ",
"                      ################                  ##############                                                              ",
"                      ################                  ##############                                                              ",
"                    ################                    ##############                                                              ",
"                    ################                    ##############                                                              ",
"                  ##############                        ##############                                                              ",
"                  ##############                        ##############                                                              ",
"              ################                            ############                                                              ",
"              ################                            ############                                                              ",
"          ##################                              ############                                                              ",
"          ##################                              ############                                                              ",
"  OOOOOO..################                                  ########                                                                ",
"  OOOOOO..################                                  ########                                                                ",
"OOOOOOOO..########                                            ....                                                                  ",
"OOOOOOOO..########                                            ....                                                                  ",
"OOOOOO                                                        OOOO                                                                  ",
"OOOOOO                                                        OOOO                                                                  ",
"OOO                                                         OOOOOOOOOO                                                              ",
"OOO                                                         OOOOOOOOOO                                                              ",
"OOO                                                         OOOOOOOOOOOOOOOO                                                        ",
"OOO                                                         OOOOOOOOOOOOOOOO                                                        "
};

/* XPM */
static xpm_row_t const spikes_dead[] = {
/* columns rows colors chars-per-pixel */
"88 56 8 1 ",
"  c None",
". c #B60909",
"X c #C76100",
"o c #FFBA78",
"O c #FFD969",
"+ c #ACACAC",
"@ c #C1EEFD",
"# c #F8FFFF",
/* pixels */
"                                                                ++            ++        ",
"                                                                ++            ++        ",
"                                                                ++@@        @@++        ",
"                                                                ++@@        @@++        ",
"                                                              @@++++        ++++        ",
"                                                              @@++++        ++++        ",
"                                                              ++++++@@      ++++        ",
"                                                              ++++++@@      ++++        ",
"                                                ++            ++++++++    @@++++        ",
"                                                ++            ++++++++    @@++++        ",
"                                                ++@@        @@++++++++@@  ++++++        ",
"                                                ++@@        @@++++++++@@  ++++++        ",
"                                              @@++++        ++++++++++++  ++++++        ",
"                                              @@++++        ++++++++++++  ++++++        ",
"                                              ++++++@@      ++++++++++++  ++++++        ",
"                                              ++++++@@      ++++++++++++  ++++++        ",
"                                ++            ++++++++    @@++++++++++++++++++++        ",
"                                ++            ++++++++    @@++++++++++++++++++++        ",
"                                ++@@        @@++++++++@@  ++++++++++++++++++++++        ",
"                                ++@@        @@++++++++@@  ++++++++++++++++++++++        ",
"                                ++++        ++++..++++++  ++++++++++++++++++++++        ",
"                                ++++        ++++..++++++  ++++++++++++++++++++++        ",
"                        oooooooo++++@@      ++++++..++++  ++++++++++++++++++++++        ",
"                        oooooooo++++@@      ++++++..++++  ++++++++++++++++++++++        ",
"                      ##oooooooo++++++    @@++++++++..++++++++++++++++++++++++++        ",
"                      ##oooooooo++++++    @@++++++++..++++++++++++++++++++++++++        ",
"                    ####oooooooo++++++@@  ++++++..++########oooo++++++++++++++++        ",
"                    ####oooooooo++++++@@  ++++++..++########oooo++++++++++++++++        ",
"                  oo########oooo++++++++  ++++++..##############++++++++++++++++        ",
"                  oo########oooo++++++++  ++++++..##############++++++++++++++++        ",
"    OOOOOOOOOOOOoo##############++++++++  ++++++..################++++++++++++++        ",
"    OOOOOOOOOOOOoo##############++++++++  ++++++..################++++++++++++++        ",
"  OOOOOOOOOOoooooo##############++++++++++++++++####################++++++++            ",
"  OOOOOOOOOOoooooo##############++++++++++++++++####################++++++++            ",
"OOOOOOOOoooooooooooo##########oo++++++++++++++++##oooo##############++++                ",
"OOOOOOOOoooooooooooo##########oo++++++++++++++++##oooo##############++++                ",
"OOOOOOOOOOooooooooOOOOoo####oooo++++++++++++++++####oo####################oooooooooo    ",
"OOOOOOOOOOooooooooOOOOoo####oooo++++++++++++++++####oo####################oooooooooo    ",
"OOOOOOOOOOooooooooOOoooooooooooo++++++++++++++++######oooo################oooooooooo    ",
"OOOOOOOOOOooooooooOOooooooXXoooo++++++++++++++++######oooo################oooooooooo    ",
"    OOOOOOOOOOOOOOooooooooXXoo..++++++++++++++++oo######oooooooo########oooooooooooooooo",
"    OOOOOOOOOOOOOOoooooooooooo..++++++++++++++++oo######oooooooo########oooooooooooooooo",
"                XXXXXXoooooooooo++++++++++++++++oooo..oooooooooooooooooooooooooooooooooo",
"                XXXXXXoooooooooo++++++++++++++++oooo..oooooooooooooooooooooooooooooooooo",
"            XXXXXXXXXXoooooooo..++++++++++++++++oooooooo....oooooooooooooo              ",
"            XXXXXXXXXXoooooooo..++++++++++++++++oooooooo....oooooooooooooo              ",
"                          ....  ++++++++++++++++@@@@        ......  ..                  ",
"                          ....  ++++++++++++++++@@@@        ......  ..                  ",
"                        ..      ++++++++++++@@@@                ....                    ",
"                        ..      ++++++++++++@@@@                ....                    ",
"                                ++++++++@@@@                                            ",
"                                ++++++++@@@@                                            ",
"                                ++++@@@@                                                ",
"                                ++++@@@@                                                ",
"                                @@@@                                                    ",
"                                @@@@                                                    "
};
